-- iPOS Backup | Label: with_new_feature_global_announcement_and_maintenance | Created: 2026-05-20 06:38:38
-- Generated by iPOS Superadmin Backup & Recovery

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `admin_extended`;
CREATE TABLE `admin_extended` (
  `admin_id` int NOT NULL,
  `age` int DEFAULT NULL,
  `contact_number` varchar(30) DEFAULT NULL,
  `home_address` text,
  `store_address` text,
  `store_location` varchar(100) DEFAULT NULL,
  `store_contact` varchar(30) DEFAULT NULL,
  `bir_permit` varchar(50) DEFAULT NULL,
  `logo_shape` enum('circle','square','rounded') DEFAULT 'circle',
  `logo_url` varchar(500) DEFAULT NULL,
  `profile_photo` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`admin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `admin_extended` (`admin_id`, `age`, `contact_number`, `home_address`, `store_address`, `store_location`, `store_contact`, `bir_permit`, `logo_shape`, `logo_url`, `profile_photo`) VALUES ('5', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle', NULL, '../uploads/logo_5_1779041148.jpg');

DROP TABLE IF EXISTS `admin_restore_logs`;
CREATE TABLE `admin_restore_logs` (
  `restore_id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int NOT NULL,
  `filename` varchar(255) NOT NULL,
  `restored_by` varchar(100) NOT NULL,
  `restored_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `source` enum('server','upload') NOT NULL DEFAULT 'server',
  PRIMARY KEY (`restore_id`),
  KEY `admin_id` (`admin_id`),
  CONSTRAINT `admin_restore_logs_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `admin_restore_logs` (`restore_id`, `admin_id`, `filename`, `restored_by`, `restored_at`, `source`) VALUES ('1', '3', 'backup_new_item_20260518_212441.sql', 'uzumaki', '2026-05-19 13:35:14', 'server');
INSERT INTO `admin_restore_logs` (`restore_id`, `admin_id`, `filename`, `restored_by`, `restored_at`, `source`) VALUES ('2', '3', 'backup_manual_20260519_124733.sql', 'uzumaki', '2026-05-19 13:37:21', 'server');
INSERT INTO `admin_restore_logs` (`restore_id`, `admin_id`, `filename`, `restored_by`, `restored_at`, `source`) VALUES ('3', '3', 'backup_first_backup_for_uzumaki_20260518_211720.sql', 'uzumaki', '2026-05-19 13:39:05', 'server');
INSERT INTO `admin_restore_logs` (`restore_id`, `admin_id`, `filename`, `restored_by`, `restored_at`, `source`) VALUES ('4', '3', 'backup_first_backup_for_uzumaki_20260518_211720.sql', 'uzumaki', '2026-05-19 13:42:30', 'server');
INSERT INTO `admin_restore_logs` (`restore_id`, `admin_id`, `filename`, `restored_by`, `restored_at`, `source`) VALUES ('5', '3', 'backup_first_backup_for_uzumaki_20260518_211720.sql', 'uzumaki', '2026-05-19 14:06:28', 'server');
INSERT INTO `admin_restore_logs` (`restore_id`, `admin_id`, `filename`, `restored_by`, `restored_at`, `source`) VALUES ('6', '3', 'backup_with_two_orders_and_new_staff_sakura_20260519_140551.sql', 'uzumaki', '2026-05-19 22:25:57', 'server');

DROP TABLE IF EXISTS `admin_sessions`;
CREATE TABLE `admin_sessions` (
  `session_id` varchar(255) NOT NULL,
  `admin_id` int NOT NULL,
  `login_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `logout_time` timestamp NULL DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`session_id`),
  KEY `admin_id` (`admin_id`),
  CONSTRAINT `admin_sessions_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `admin_sessions` (`session_id`, `admin_id`, `login_time`, `logout_time`, `is_active`) VALUES ('dd0ec7e3c354cdd3ddf697aa27c36a93', '1', '2026-05-20 06:37:48', NULL, '1');

DROP TABLE IF EXISTS `admins`;
CREATE TABLE `admins` (
  `admin_id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `fullname` varchar(100) NOT NULL,
  `fastfood_name` varchar(100) DEFAULT NULL,
  `role` enum('superadmin','owner') DEFAULT 'owner',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login` timestamp NULL DEFAULT NULL,
  `max_devices` int DEFAULT '1',
  `dashboard_pin` varchar(255) DEFAULT NULL,
  `phone_number` varchar(20) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `municipality` varchar(100) DEFAULT NULL,
  `province` varchar(100) DEFAULT NULL,
  `zip_code` varchar(10) DEFAULT NULL,
  `business_permit` varchar(100) DEFAULT NULL,
  `logo` varchar(255) DEFAULT NULL,
  `theme` varchar(50) DEFAULT NULL,
  `business_type` varchar(100) DEFAULT NULL,
  `dti_sec_number` varchar(100) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `logo_url` varchar(255) DEFAULT NULL,
  `logo_shape` varchar(50) DEFAULT 'circle',
  `tin_number` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`admin_id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `max_devices`, `dashboard_pin`, `phone_number`, `address`, `municipality`, `province`, `zip_code`, `business_permit`, `logo`, `theme`, `business_type`, `dti_sec_number`, `city`, `logo_url`, `logo_shape`, `tin_number`) VALUES ('1', 'superAdmin', 'ipossuperadmin@gmail.com', '$2y$12$s1jhaekLFC/MqgQf6l6LvO1jLqIyS5mlWZpLxGyejtlFTtWV2HzuS', 'System Administrator', NULL, 'superadmin', '2026-05-14 21:45:21', '2026-05-20 06:37:48', '1', '$2y$12$e9AwrvoFwYvVRzSsPo7m5eUoP7.Icjkxs4EaMqrRfPAeUoE8XNQty', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle', NULL);
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `max_devices`, `dashboard_pin`, `phone_number`, `address`, `municipality`, `province`, `zip_code`, `business_permit`, `logo`, `theme`, `business_type`, `dti_sec_number`, `city`, `logo_url`, `logo_shape`, `tin_number`) VALUES ('3', 'uzumaki', 'btsbighitarmymoa@gmail.com', '$2y$12$1t9r/DW/D/cClb74S6bFzO75U5ifg8m4y.3JFQPNso8128AovU8K2', 'Naruto Uzumaki', 'uzumaki ramen', 'owner', '2026-05-15 14:12:26', '2026-05-20 06:35:06', '1', '$2y$12$C8M.NyXl2Vu4plmw29DSg.760mQqIFyMbeRHEXLH54aJHd9pg4xjW', '09357012999', 'Tokyo Japan', NULL, '', '2134', '', NULL, NULL, 'Restaurant', '', 'Tokyo', NULL, 'circle', '123-123-3');
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `max_devices`, `dashboard_pin`, `phone_number`, `address`, `municipality`, `province`, `zip_code`, `business_permit`, `logo`, `theme`, `business_type`, `dti_sec_number`, `city`, `logo_url`, `logo_shape`, `tin_number`) VALUES ('4', 'ninagraceteroyang@gmail.com', 'ninagraceteroyang@gmail.com', '$2y$12$59B75kcN9TegpQuUaZyLku2fhr3trEwBprLLH//EY.6M01qvwQ25.', 'kath', 'cafees', 'owner', '2026-05-17 14:29:25', '2026-05-17 14:29:33', '1', NULL, '0912345346', 'Mahaplag', NULL, 'Leyte', '2134', '', NULL, NULL, 'Cafe', '', 'Mahaplag', NULL, 'circle', '123-123-3');
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `max_devices`, `dashboard_pin`, `phone_number`, `address`, `municipality`, `province`, `zip_code`, `business_permit`, `logo`, `theme`, `business_type`, `dti_sec_number`, `city`, `logo_url`, `logo_shape`, `tin_number`) VALUES ('5', 'NAtsuuu', 'hybeinsight@gmail.com', '$2y$12$aLVVSx8CdN0uJ46yoAZm/.7rCNvpclIniWkbOJURGtB1gccNGBKcW', 'Natsu', 'Fstfd', 'owner', '2026-05-17 18:01:19', '2026-05-20 06:35:38', '1', '$2y$12$KOFfcSX6QWcRKBr/2jE0KO3E0lUhzCls2jGrH.Hrqv6urzposuQpK', '09456788965', 'Mahaplag', NULL, 'Benguet', '5467', '', NULL, NULL, 'Fast Food', '', 'Kapangan', NULL, 'circle', '123-123-3');

DROP TABLE IF EXISTS `audit_log`;
CREATE TABLE `audit_log` (
  `log_id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int DEFAULT NULL,
  `actor_name` varchar(100) NOT NULL DEFAULT '',
  `action` varchar(80) NOT NULL,
  `target_type` varchar(50) DEFAULT NULL,
  `target_id` int DEFAULT NULL,
  `target_label` varchar(200) DEFAULT NULL,
  `detail` text,
  `ip_address` varchar(45) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  KEY `admin_id` (`admin_id`),
  CONSTRAINT `audit_log_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=65 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('1', '1', 'superAdmin', 'superadmin_credentials_updated', 'superadmin', '1', 'superAdmin', 'Username and email updated', '::1', '2026-05-15 11:35:15');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('2', '1', 'superAdmin', 'backup_created', 'backup', NULL, 'backup_manual_20260515_140547.sql', 'Backup label: manual, tables: 10', '::1', '2026-05-15 14:05:47');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('3', '1', 'superAdmin', 'superadmin_logout', 'superadmin', '1', 'superAdmin', 'Superadmin logged out', '::1', '2026-05-15 14:07:55');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('4', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-15 14:08:08');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('5', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-15 14:08:09');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('6', '1', 'superAdmin', 'superadmin_logout', 'superadmin', '1', 'superAdmin', 'Superadmin logged out', '::1', '2026-05-15 14:08:20');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('7', NULL, 'superadmin', 'owner_created', 'owner', NULL, 'uzumaki', 'New owner registered: uzumaki (uzumaki ramen)', '::1', '2026-05-15 14:12:27');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('8', NULL, 'uzumaki', 'failed_login_attempt', NULL, NULL, 'uzumaki', 'Failed login attempt for username: uzumaki', '::1', '2026-05-15 14:16:28');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('9', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-15 14:16:38');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('10', '1', 'superAdmin', 'owner_deleted', 'owner', '2', 'jinwoo', 'Deleted owner: jinwoo (solo)', '::1', '2026-05-15 14:17:28');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('11', '1', 'superAdmin', 'superadmin_logout', 'superadmin', '1', 'superAdmin', 'Superadmin logged out', '::1', '2026-05-15 14:18:59');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('12', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-15 14:29:54');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('13', '1', 'superAdmin', 'superadmin_logout', 'superadmin', '1', 'superAdmin', 'Superadmin logged out', '::1', '2026-05-15 14:59:11');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('14', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-16 11:45:52');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('15', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-16 18:31:07');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('16', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-17 14:04:14');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('17', '1', 'superAdmin', 'superadmin_logout', 'superadmin', '1', 'superAdmin', 'Superadmin logged out', '::1', '2026-05-17 14:28:07');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('18', NULL, 'superadmin', 'owner_created', 'owner', NULL, 'ninagraceteroyang@gmail.com', 'New owner registered: ninagraceteroyang@gmail.com (cafees)', '::1', '2026-05-17 14:29:25');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('19', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-17 14:35:51');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('20', '1', 'superAdmin', 'backup_created', 'backup', NULL, 'backup_manual_20260517_143612.sql', 'Backup label: manual, tables: 10', '::1', '2026-05-17 14:36:12');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('21', '1', 'superAdmin', 'backup_restored', 'backup', NULL, 'backup_new_user_20260517_143621.sql', 'Database restored from: backup_new_user_20260517_143621.sql', '::1', '2026-05-17 14:44:44');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('22', '1', 'superAdmin', 'backup_deleted', 'backup', NULL, 'backup_manual_20260515_140547.sql', 'Backup file deleted: backup_manual_20260515_140547.sql', '::1', '2026-05-17 14:51:48');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('23', '1', 'superAdmin', 'superadmin_logout', 'superadmin', '1', 'superAdmin', 'Superadmin logged out', '::1', '2026-05-17 17:59:38');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('24', NULL, 'superadmin', 'owner_created', 'owner', NULL, 'NAtsuuu', 'New owner registered: NAtsuuu (Fstfd)', '::1', '2026-05-17 18:01:19');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('25', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-17 18:18:35');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('26', '1', 'superAdmin', 'backup_created', 'backup', NULL, 'backup_New_user_natsu_20260517_181858.sql', 'Backup label: New_user_natsu, tables: 11', '::1', '2026-05-17 18:18:59');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('27', '1', 'superAdmin', 'backup_deleted', 'backup', NULL, 'backup_New_user_natsu_20260517_181858.sql', 'Backup file deleted: backup_New_user_natsu_20260517_181858.sql', '::1', '2026-05-17 18:19:46');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('28', '1', 'superAdmin', 'backup_restored', 'backup', NULL, 'backup_new_user_natsu_20260517_182013.sql', 'Database restored from: backup_new_user_natsu_20260517_182013.sql', '::1', '2026-05-19 15:58:30');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('29', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-19 21:06:13');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('30', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-19 21:06:14');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('31', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-19 22:15:01');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('32', '1', 'superAdmin', 'superadmin_credentials_updated', 'superadmin', '1', 'superAdmin', 'Username and email updated', '::1', '2026-05-19 22:19:29');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('33', '1', 'superAdmin', 'superadmin_logout', 'superadmin', '1', 'superAdmin', 'Superadmin logged out', '::1', '2026-05-19 22:21:09');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('34', '3', 'uzumaki', 'admin_backup_restored', 'backup', NULL, 'backup_manual_20260519_124733.sql', 'Admin database restored from: backup_manual_20260519_124733.sql', '::1', '2026-05-19 13:24:14');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('35', '3', 'uzumaki', 'admin_backup_restored', 'backup', NULL, 'backup_manual_20260519_124733.sql', 'Admin database restored from: backup_manual_20260519_124733.sql', '::1', '2026-05-19 13:27:00');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('44', '3', 'uzumaki', 'admin_backup_created', 'backup', NULL, 'backup_first_backup_for_uzumaki_20260518_211720.sql', 'Admin backup created: backup_first_backup_for_uzumaki_20260518_211720.sql | menu:0, staff:1, orders:0', '::1', '2026-05-18 21:17:20');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('45', '3', 'uzumaki', 'admin_backup_restored', 'backup', NULL, 'backup_new_item_20260518_212441.sql', 'Admin database restored from: backup_new_item_20260518_212441.sql', '::1', '2026-05-19 13:35:14');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('46', '3', 'uzumaki', 'admin_backup_created', 'backup', NULL, 'backup_with_nissin_ramen_new_item_20260519_133704.sql', 'Admin backup created: backup_with_nissin_ramen_new_item_20260519_133704.sql | menu:2, staff:1, orders:0', '::1', '2026-05-19 13:37:04');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('47', '3', 'uzumaki', 'admin_backup_restored', 'backup', NULL, 'backup_manual_20260519_124733.sql', 'Admin database restored from: backup_manual_20260519_124733.sql', '::1', '2026-05-19 13:37:21');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('48', '3', 'uzumaki', 'admin_backup_restored', 'backup', NULL, 'backup_first_backup_for_uzumaki_20260518_211720.sql', 'Admin database restored from: backup_first_backup_for_uzumaki_20260518_211720.sql', '::1', '2026-05-19 13:39:05');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('49', '3', 'uzumaki', 'admin_backup_restored', 'backup', NULL, 'backup_first_backup_for_uzumaki_20260518_211720.sql', 'Admin database restored from: backup_first_backup_for_uzumaki_20260518_211720.sql', '::1', '2026-05-19 13:42:30');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('50', '3', 'uzumaki', 'admin_backup_restored', 'backup', NULL, 'backup_with_two_orders_and_new_staff_sakura_20260519_140551.sql', 'Admin database restored from: backup_with_two_orders_and_new_staff_sakura_20260519_140551.sql', '::1', '2026-05-19 22:25:57');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('51', NULL, 'superadmin', 'failed_login_attempt', NULL, NULL, 'superadmin', 'Failed login attempt for username: superadmin', '::1', '2026-05-19 23:10:39');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('52', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-19 23:10:58');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('53', '1', 'superAdmin', 'superadmin_logout', 'superadmin', '1', 'superAdmin', 'Superadmin logged out', '::1', '2026-05-20 05:24:22');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('54', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-20 06:18:10');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('55', '1', 'superAdmin', 'maintenance_updated', 'superadmin', '1', 'superAdmin', 'Maintenance mode ENABLED', '::1', '2026-05-20 06:22:25');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('56', '1', 'superAdmin', 'announcement_updated', 'superadmin', '1', 'superAdmin', 'Announcement set to ENABLED (type: info)', '::1', '2026-05-20 06:22:28');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('57', '1', 'superAdmin', 'superadmin_logout', 'superadmin', '1', 'superAdmin', 'Superadmin logged out', '::1', '2026-05-20 06:22:48');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('58', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-20 06:28:53');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('59', '1', 'superAdmin', 'maintenance_toggled', 'superadmin', '1', 'superAdmin', 'Maintenance mode toggled to OFF', '::1', '2026-05-20 06:29:01');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('60', '1', 'superAdmin', 'announcement_updated', 'superadmin', '1', 'superAdmin', 'Announcement set to ENABLED (type: info)', '::1', '2026-05-20 06:29:37');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('61', '1', 'superAdmin', 'announcement_updated', 'superadmin', '1', 'superAdmin', 'Announcement set to ENABLED (type: info)', '::1', '2026-05-20 06:29:40');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('62', '1', 'superAdmin', 'announcement_updated', 'superadmin', '1', 'superAdmin', 'Announcement set to ENABLED (type: info)', '::1', '2026-05-20 06:29:43');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('63', '1', 'superAdmin', 'superadmin_logout', 'superadmin', '1', 'superAdmin', 'Superadmin logged out', '::1', '2026-05-20 06:29:46');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('64', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-20 06:37:49');

DROP TABLE IF EXISTS `carts`;
CREATE TABLE `carts` (
  `cart_id` int NOT NULL AUTO_INCREMENT,
  `customer_id` int NOT NULL,
  `menu_item_id` int NOT NULL,
  `quantity` int NOT NULL DEFAULT '1',
  `subtotal` decimal(10,2) NOT NULL DEFAULT '0.00',
  `date_added` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cart_id`),
  KEY `customer_id` (`customer_id`),
  KEY `menu_item_id` (`menu_item_id`),
  CONSTRAINT `carts_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`customer_id`) ON DELETE CASCADE,
  CONSTRAINT `carts_ibfk_2` FOREIGN KEY (`menu_item_id`) REFERENCES `menu_items` (`menu_item_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `customers`;
CREATE TABLE `customers` (
  `customer_id` int NOT NULL AUTO_INCREMENT,
  `order_number` varchar(20) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `table_number` varchar(20) DEFAULT NULL,
  `session_start` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `session_end` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `customers` (`customer_id`, `order_number`, `name`, `table_number`, `session_start`, `session_end`) VALUES ('1', 'ORD-00001', NULL, '1', '2026-05-17 18:12:46', NULL);
INSERT INTO `customers` (`customer_id`, `order_number`, `name`, `table_number`, `session_start`, `session_end`) VALUES ('2', 'ORD-00002', NULL, '2', '2026-05-17 18:13:04', NULL);
INSERT INTO `customers` (`customer_id`, `order_number`, `name`, `table_number`, `session_start`, `session_end`) VALUES ('3', 'ORD-00003', NULL, '3', '2026-05-17 18:13:47', NULL);

DROP TABLE IF EXISTS `menu_items`;
CREATE TABLE `menu_items` (
  `menu_item_id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int NOT NULL,
  `item_name` varchar(120) NOT NULL,
  `description` text,
  `price` decimal(10,2) NOT NULL,
  `stock_quantity` int NOT NULL DEFAULT '0',
  `category` varchar(60) NOT NULL DEFAULT 'Uncategorized',
  `is_available` tinyint(1) NOT NULL DEFAULT '1',
  `image_url` varchar(500) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`menu_item_id`),
  KEY `admin_id` (`admin_id`),
  CONSTRAINT `menu_items_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('1', '4', 'ice coffee', 'coffee', '49.00', '100', 'coffee', '1', NULL, '2026-05-17 14:31:42', '2026-05-17 14:31:42');
INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('2', '4', 'hot choco', 'choco lattee', '49.00', '100', 'hot lattee', '1', NULL, '2026-05-17 14:32:41', '2026-05-17 14:32:41');
INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('3', '5', 'isaw', '', '7.00', '100', 'isaw', '1', NULL, '2026-05-17 18:02:54', '2026-05-17 18:02:54');
INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('4', '5', 'hotdog', '', '20.00', '150', 'hotdog', '1', NULL, '2026-05-17 18:03:26', '2026-05-17 18:03:26');
INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('5', '5', 'quick2', '', '10.00', '96', 'quick2', '1', NULL, '2026-05-17 18:04:07', '2026-05-17 18:13:47');
INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('7', '3', 'buldak', '', '50.00', '99', 'dry noodles', '1', '../uploads/item_3_1779139422.jpg', '2026-05-18 21:23:48', '2026-05-19 13:50:30');
INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('8', '3', 'nissin ramen', '', '45.00', '199', 'Noodles', '1', '../uploads/item_3_1779197805.jpg', '2026-05-19 13:36:49', '2026-05-19 13:48:53');

DROP TABLE IF EXISTS `order_items`;
CREATE TABLE `order_items` (
  `order_item_id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `menu_item_id` int DEFAULT NULL,
  `item_name` varchar(120) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `quantity` int NOT NULL,
  `subtotal` decimal(10,2) NOT NULL,
  PRIMARY KEY (`order_item_id`),
  KEY `order_id` (`order_id`),
  KEY `menu_item_id` (`menu_item_id`),
  CONSTRAINT `order_items_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`order_id`) ON DELETE CASCADE,
  CONSTRAINT `order_items_ibfk_2` FOREIGN KEY (`menu_item_id`) REFERENCES `menu_items` (`menu_item_id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('1', '1', '5', 'quick2', '10.00', '1', '10.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('2', '2', '5', 'quick2', '10.00', '1', '10.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('3', '3', '5', 'quick2', '10.00', '2', '20.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('4', '4', '8', 'nissin ramen', '45.00', '1', '45.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('5', '5', '7', 'buldak', '50.00', '1', '50.00');

DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders` (
  `order_id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int NOT NULL,
  `customer_id` int NOT NULL,
  `order_status` enum('Queued','Preparing','Served','Completed','Cancelled') NOT NULL DEFAULT 'Queued',
  `total_amount` decimal(10,2) NOT NULL DEFAULT '0.00',
  `queue_number` int NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`order_id`),
  KEY `admin_id` (`admin_id`),
  KEY `customer_id` (`customer_id`),
  CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE CASCADE,
  CONSTRAINT `orders_ibfk_2` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`customer_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`, `updated_at`) VALUES ('1', '5', '1', 'Served', '10.00', '1', '2026-05-17 18:12:46', '2026-05-17 18:17:53');
INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`, `updated_at`) VALUES ('2', '5', '2', 'Served', '10.00', '2', '2026-05-17 18:13:04', '2026-05-17 18:17:56');
INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`, `updated_at`) VALUES ('3', '5', '3', 'Served', '20.00', '3', '2026-05-17 18:13:47', '2026-05-17 18:18:00');
INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`, `updated_at`) VALUES ('4', '3', '4', 'Queued', '45.00', '1', '2026-05-19 13:48:53', '2026-05-19 13:48:53');
INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`, `updated_at`) VALUES ('5', '3', '5', 'Queued', '50.00', '2', '2026-05-19 13:50:30', '2026-05-19 13:50:30');

DROP TABLE IF EXISTS `payments`;
CREATE TABLE `payments` (
  `payment_id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `payment_method` enum('Cash','GCash','Credit Card') NOT NULL DEFAULT 'Cash',
  `amount_paid` decimal(10,2) NOT NULL,
  `change_given` decimal(10,2) NOT NULL DEFAULT '0.00',
  `receipt_number` varchar(30) NOT NULL,
  `payment_status` enum('Completed','Pending','Failed') NOT NULL DEFAULT 'Pending',
  `payment_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`payment_id`),
  UNIQUE KEY `order_id` (`order_id`),
  UNIQUE KEY `receipt_number` (`receipt_number`),
  CONSTRAINT `payments_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`order_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('1', '1', 'Cash', '50.00', '40.00', 'RCP-6A0A051E6318A', 'Completed', '2026-05-17 18:12:46');
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('2', '2', 'Cash', '100.00', '90.00', 'RCP-6A0A053039754', 'Completed', '2026-05-17 18:13:04');
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('3', '3', 'Cash', '50.00', '30.00', 'RCP-6A0A055B344FC', 'Completed', '2026-05-17 18:13:47');
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('4', '4', 'Cash', '100.00', '55.00', 'RCP-6A0C6A459B696', 'Completed', '2026-05-19 13:48:53');
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('5', '5', 'Cash', '100.00', '50.00', 'RCP-6A0C6AA6088A2', 'Completed', '2026-05-19 13:50:30');

DROP TABLE IF EXISTS `staffs`;
CREATE TABLE `staffs` (
  `staff_id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int NOT NULL,
  `fullname` varchar(100) NOT NULL,
  `role` enum('Cashier','Kitchen') NOT NULL DEFAULT 'Cashier',
  `pin` varchar(255) DEFAULT NULL,
  `status` enum('Active','Inactive') NOT NULL DEFAULT 'Active',
  `shift_start` time DEFAULT NULL,
  `shift_end` time DEFAULT NULL,
  `login_fail_count` int NOT NULL DEFAULT '0',
  `last_fail_at` timestamp NULL DEFAULT NULL,
  `last_login_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`staff_id`),
  KEY `admin_id` (`admin_id`),
  CONSTRAINT `staffs_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`) VALUES ('2', '3', 'hinata', 'Cashier', '$2y$12$yO4a3pZOFpPfNcOW8thDI.8/wIYh5502PiBVptOtjOLG16SgkG0y.', 'Active', '13:15:00', '17:15:00', '1', '2026-05-20 05:25:59', '2026-05-19 13:48:40', '2026-05-15 14:14:35');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`) VALUES ('3', '5', 'hapi', 'Cashier', '$2y$12$THbOPJRCL2EXeEdcozQxquDpgZ.7Zq1gzLJ3GXl9F.TxcuauflK/a', 'Active', '06:01:00', '18:00:00', '0', NULL, '2026-05-17 18:10:03', '2026-05-17 18:05:08');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`) VALUES ('4', '5', 'lucy', 'Kitchen', '$2y$12$P9jTgmGHpW7ukFza64QyF.FuA02Q2mGP7HFOKx1PA50aDF/mNDFd.', 'Active', '06:00:00', '18:00:00', '0', NULL, '2026-05-17 18:17:42', '2026-05-17 18:12:13');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`) VALUES ('5', '3', 'sakura', 'Cashier', '$2y$12$q0UwR8hS0Btx8uyrsR.T1Or61T8jlqugQQgMT94K5YvsZRm/D8XC6', 'Active', '05:46:00', '18:50:00', '3', '2026-05-20 05:25:45', NULL, '2026-05-19 13:47:16');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`) VALUES ('6', '3', 'hima', 'Kitchen', '$2y$12$2PCUeyPU.Zw2oE3JFEI/4O6XwmdCky.l0YRHHhFB5rQm/nQcyBR3K', 'Active', '05:27:00', '17:27:00', '0', NULL, NULL, '2026-05-20 05:27:42');

DROP TABLE IF EXISTS `system_settings`;
CREATE TABLE `system_settings` (
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  PRIMARY KEY (`setting_key`),
  KEY `updated_by` (`updated_by`),
  CONSTRAINT `system_settings_ibfk_1` FOREIGN KEY (`updated_by`) REFERENCES `admins` (`admin_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `system_settings` (`setting_key`, `setting_value`, `updated_at`, `updated_by`) VALUES ('announcement_enabled', '1', '2026-05-20 06:29:43', '1');
INSERT INTO `system_settings` (`setting_key`, `setting_value`, `updated_at`, `updated_by`) VALUES ('announcement_message', 'The system has new feature try it now!', '2026-05-20 06:29:43', '1');
INSERT INTO `system_settings` (`setting_key`, `setting_value`, `updated_at`, `updated_by`) VALUES ('announcement_type', 'info', '2026-05-20 06:29:43', '1');
INSERT INTO `system_settings` (`setting_key`, `setting_value`, `updated_at`, `updated_by`) VALUES ('maintenance_enabled', '0', '2026-05-20 06:29:00', '1');
INSERT INTO `system_settings` (`setting_key`, `setting_value`, `updated_at`, `updated_by`) VALUES ('maintenance_end_time', NULL, '2026-05-20 06:22:25', '1');
INSERT INTO `system_settings` (`setting_key`, `setting_value`, `updated_at`, `updated_by`) VALUES ('maintenance_message', 'System on maintenance', '2026-05-20 06:22:25', '1');

DROP TABLE IF EXISTS `user_backup_logs`;
CREATE TABLE `user_backup_logs` (
  `log_id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int NOT NULL,
  `backup_type` enum('menu_json','menu_csv','sales_csv') NOT NULL,
  `period` varchar(20) DEFAULT NULL,
  `downloaded_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  KEY `admin_id` (`admin_id`),
  CONSTRAINT `user_backup_logs_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `user_backup_logs` (`log_id`, `admin_id`, `backup_type`, `period`, `downloaded_at`) VALUES ('1', '1', 'menu_json', NULL, '2026-05-18 21:14:26');

SET FOREIGN_KEY_CHECKS=1;
