-- iPOS Backup | Label: hatdog | Created: 2026-05-20 21:00:43
-- Generated by iPOS Superadmin Backup & Recovery

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `admin_extended`;
CREATE TABLE `admin_extended` (
  `admin_id` int NOT NULL,
  `age` int DEFAULT NULL,
  `contact_number` varchar(30) DEFAULT NULL,
  `home_address` text,
  `store_address` text,
  `store_location` varchar(100) DEFAULT NULL,
  `store_contact` varchar(30) DEFAULT NULL,
  `bir_permit` varchar(50) DEFAULT NULL,
  `logo_shape` enum('circle','square','rounded') DEFAULT 'circle',
  `logo_url` varchar(500) DEFAULT NULL,
  `profile_photo` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`admin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `admin_extended` (`admin_id`, `age`, `contact_number`, `home_address`, `store_address`, `store_location`, `store_contact`, `bir_permit`, `logo_shape`, `logo_url`, `profile_photo`) VALUES ('3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle', '../uploads/logo_3_1779305154.png', '../uploads/logo_3_1779305224.png');
INSERT INTO `admin_extended` (`admin_id`, `age`, `contact_number`, `home_address`, `store_address`, `store_location`, `store_contact`, `bir_permit`, `logo_shape`, `logo_url`, `profile_photo`) VALUES ('10', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle', '../uploads/logo_10_1779261076.jfif', NULL);

DROP TABLE IF EXISTS `admin_sessions`;
CREATE TABLE `admin_sessions` (
  `session_id` varchar(255) NOT NULL,
  `admin_id` int NOT NULL,
  `login_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `logout_time` timestamp NULL DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`session_id`),
  KEY `admin_id` (`admin_id`),
  CONSTRAINT `admin_sessions_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `admin_sessions` (`session_id`, `admin_id`, `login_time`, `logout_time`, `is_active`) VALUES ('510a1a6043559209ecc58952506b711b', '1', '2026-05-21 05:00:32', NULL, '1');
INSERT INTO `admin_sessions` (`session_id`, `admin_id`, `login_time`, `logout_time`, `is_active`) VALUES ('51771712c29866bd9d3f9788d8fa1eca', '3', '2026-05-21 03:25:17', NULL, '0');
INSERT INTO `admin_sessions` (`session_id`, `admin_id`, `login_time`, `logout_time`, `is_active`) VALUES ('b53d9602b3445cb0e30f7559d5b9a93d', '8', '2026-05-08 07:05:13', NULL, '0');

DROP TABLE IF EXISTS `admins`;
CREATE TABLE `admins` (
  `admin_id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `fullname` varchar(100) NOT NULL,
  `fastfood_name` varchar(100) DEFAULT NULL,
  `role` enum('superadmin','owner') DEFAULT 'owner',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login` timestamp NULL DEFAULT NULL,
  `dashboard_pin` varchar(255) DEFAULT NULL,
  `theme_data` text,
  `phone_number` varchar(20) DEFAULT NULL,
  `business_type` varchar(50) DEFAULT NULL,
  `tin_number` varchar(30) DEFAULT NULL,
  `dti_sec_number` varchar(50) DEFAULT NULL,
  `business_permit` varchar(50) DEFAULT NULL,
  `address` text,
  `city` varchar(100) DEFAULT NULL,
  `province` varchar(100) DEFAULT NULL,
  `zip_code` varchar(10) DEFAULT NULL,
  `logo_url` varchar(255) DEFAULT NULL,
  `logo_shape` varchar(20) DEFAULT 'circle',
  PRIMARY KEY (`admin_id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `dashboard_pin`, `theme_data`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`) VALUES ('1', 'superadmin', 'ipossuperadmin@gmail.com', '$2y$12$s1jhaekLFC/MqgQf6l6LvO1jLqIyS5mlWZpLxGyejtlFTtWV2HzuS', 'System Administrator', NULL, 'superadmin', '2026-04-23 10:42:28', '2026-05-21 05:00:32', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle');
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `dashboard_pin`, `theme_data`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`) VALUES ('3', 'jollybee', 'ozaukeevine@gmail.com', '$2y$12$iI7DtOYHBFv9/DOfdk0LNeA21D0yLlCxM/ziEB6TyKs.svn0zdmlG', 'Veniel Ozaukee', 'Jollibee', 'owner', '2026-04-26 00:20:01', '2026-05-21 03:25:17', '$2y$12$OKBRHTvvuXNCCsfIDZHEbuTSkLdmbPWXau9g38hyL7f3MQFAGehmi', '{\"sidebarBg\":\"#2D0B22\",\"accent\":\"#BE185D\",\"accentDark\":\"#9B2C52\",\"bodyBg\":\"#f5eef4\",\"text\":\"#2d0a1f\",\"accentLight\":\"#f5eef4\",\"borderColor\":\"#f0dfe5\",\"textSec\":\"#c38097\"}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle');
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `dashboard_pin`, `theme_data`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`) VALUES ('6', 'primobbnipaeng', 'primo@gmail.com', '$2y$12$WK1AT2GrVZF0cANVvndKWeqE4UnlR6KBVcdZYuHCtMvtAvMh/vfw2', 'Primo Azarius', 'Primo\'s Lugawan', 'owner', '2026-04-26 00:46:38', '2026-04-26 20:26:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle');
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `dashboard_pin`, `theme_data`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`) VALUES ('7', 'alicia', 'alice@gmail.com', '$2y$12$QEkxKhAkbEqfMINaEv6p6Ozis160EWGn7GeOoPGqZ/nzj.Gof1Xs2', 'Johnmark Januyan', 'Johnmark\'s', 'owner', '2026-04-26 20:44:46', '2026-04-27 16:58:49', '$2y$12$o6VytmLC71IFZvHr6ygjIey/Hf8RHePC.BIkwsJRhpIjTpq8mq3OW', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle');
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `dashboard_pin`, `theme_data`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`) VALUES ('8', 'renellerosej@gmail.com', 'renellerosej@gmail.com', '$2y$12$PUUJr365/GxacAlBQ0U50OT5UbmF9NqqoDjPIeJjjuE7I0SFzGBYq', 'Renelle Rose', 'Jema BBQ', 'owner', '2026-05-07 05:09:50', '2026-05-08 07:05:13', '$2y$12$QB8bVbgFHIXD8Ium9xuTVeYhC0s7W6rE5EXBxGS330UGYP2QLUsrO', '{\"sidebarBg\":\"#0c4a6e\",\"accent\":\"#0284c7\",\"accentDark\":\"#0c4a6e\",\"bodyBg\":\"#eff8ff\",\"text\":\"#0c2340\",\"accentLight\":\"#eff8ff\",\"borderColor\":\"#dbe4e9\",\"textSec\":\"#6d92a8\"}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle');
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `dashboard_pin`, `theme_data`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`) VALUES ('9', 'miles', 'miles@gmail.com', '$2y$12$.ONCOpzsqcC2Q9d.CmiMK.Ysg97SV3yu3betFfT.BtU9Tfl0l4Vj6', 'miles vales', 'tamis', 'owner', '2026-05-08 09:35:10', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle');
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `dashboard_pin`, `theme_data`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`) VALUES ('10', 'lababyniimo', 'rj@gmail.com', '$2y$12$aScR2eLGdAuu5jkP/5Ce8e/6CTigsMCmXMQiRwRmfQQxA4un2n6s6', 'Red Almonte', 'AratNa', 'owner', '2026-05-20 15:08:21', '2026-05-20 15:10:43', '$2y$12$9x6mfj.g0sPRiDClBOEXNuN9zHxaP0SYjJQP6hiW69GLIkg6jkTGu', NULL, '09123456745', 'Fast Food', '123-456-789-0', '345679034567', '3456778', 'Katunggan Street', 'Padre Burgos', 'Southern Leyte', '6602', 'dashboard/uploads/logos/logo_1779260900_6a0d5de48f15f.png', 'square');

DROP TABLE IF EXISTS `audit_log`;
CREATE TABLE `audit_log` (
  `log_id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int DEFAULT NULL,
  `actor_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `action` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `target_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `target_id` int DEFAULT NULL,
  `target_label` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `detail` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `ip_address` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  KEY `admin_id` (`admin_id`),
  CONSTRAINT `audit_log_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('1', '1', 'superadmin', 'superadmin_logout', 'superadmin', '1', 'superadmin', 'Superadmin logged out', '::1', '2026-05-20 21:15:04');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('2', NULL, 'jollybee', 'failed_login_attempt', NULL, NULL, 'jollybee', 'Failed login attempt for username: jollybee', '::1', '2026-05-20 21:15:17');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('3', '1', 'superadmin', 'superadmin_login', 'superadmin', '1', 'superadmin', 'Superadmin logged in successfully', '::1', '2026-05-20 21:15:36');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('4', '1', 'superadmin', 'backup_restored', 'backup', NULL, 'backup_fisrttry_20260520_130321.sql', 'Database restored from: backup_fisrttry_20260520_130321.sql', '::1', '2026-05-20 21:15:46');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('5', '1', 'superadmin', 'superadmin_logout', 'superadmin', '1', 'superadmin', 'Superadmin logged out', '::1', '2026-05-20 21:16:25');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('6', '1', 'superadmin', 'superadmin_login', 'superadmin', '1', 'superadmin', 'Superadmin logged in successfully', '::1', '2026-05-20 21:31:25');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('7', '1', 'superadmin', 'superadmin_login', 'superadmin', '1', 'superadmin', 'Superadmin logged in successfully', '::1', '2026-05-21 00:49:34');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('8', '1', 'superadmin', 'superadmin_logout', 'superadmin', '1', 'superadmin', 'Superadmin logged out', '::1', '2026-05-21 01:08:34');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('9', '1', 'superadmin', 'superadmin_login', 'superadmin', '1', 'superadmin', 'Superadmin logged in successfully', '::1', '2026-05-21 01:10:26');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('10', '1', 'superadmin', 'superadmin_logout', 'superadmin', '1', 'superadmin', 'Superadmin logged out', '::1', '2026-05-21 01:22:07');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('11', '1', 'superadmin', 'superadmin_login', 'superadmin', '1', 'superadmin', 'Superadmin logged in successfully', '::1', '2026-05-21 01:40:37');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('12', '1', 'superadmin', 'backup_restored', 'backup', NULL, 'backup_sample_20260520_174059.sql', 'Database restored from: backup_sample_20260520_174059.sql', '::1', '2026-05-21 01:44:16');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('13', '1', 'superadmin', 'backup_restored', 'backup', NULL, 'backup_sample2_20260520_174822.sql', 'Database restored from: backup_sample2_20260520_174822.sql', '::1', '2026-05-21 01:51:24');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('14', '1', 'superadmin', 'superadmin_logout', 'superadmin', '1', 'superadmin', 'Superadmin logged out', '::1', '2026-05-21 01:53:02');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('15', '1', 'superadmin', 'superadmin_login', 'superadmin', '1', 'superadmin', 'Superadmin logged in successfully', '::1', '2026-05-21 05:00:32');

DROP TABLE IF EXISTS `carts`;
CREATE TABLE `carts` (
  `cart_id` int NOT NULL AUTO_INCREMENT,
  `customer_id` int NOT NULL,
  `menu_item_id` int NOT NULL,
  `quantity` int NOT NULL DEFAULT '1',
  `subtotal` decimal(10,2) NOT NULL DEFAULT '0.00',
  `date_added` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cart_id`),
  KEY `customer_id` (`customer_id`),
  KEY `menu_item_id` (`menu_item_id`),
  CONSTRAINT `carts_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`customer_id`) ON DELETE CASCADE,
  CONSTRAINT `carts_ibfk_2` FOREIGN KEY (`menu_item_id`) REFERENCES `menu_items` (`menu_item_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `customers`;
CREATE TABLE `customers` (
  `customer_id` int NOT NULL AUTO_INCREMENT,
  `order_number` varchar(20) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `table_number` varchar(20) DEFAULT NULL,
  `session_start` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `session_end` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `customers` (`customer_id`, `order_number`, `name`, `table_number`, `session_start`, `session_end`) VALUES ('1', 'ORD-00001', NULL, '1', '2026-04-27 00:03:05', NULL);
INSERT INTO `customers` (`customer_id`, `order_number`, `name`, `table_number`, `session_start`, `session_end`) VALUES ('2', 'ORD-00002', NULL, '2', '2026-04-27 17:07:50', NULL);
INSERT INTO `customers` (`customer_id`, `order_number`, `name`, `table_number`, `session_start`, `session_end`) VALUES ('3', 'ORD-00003', NULL, '3', '2026-04-27 17:30:12', NULL);
INSERT INTO `customers` (`customer_id`, `order_number`, `name`, `table_number`, `session_start`, `session_end`) VALUES ('4', 'ORD-00004', NULL, '4', '2026-04-27 17:31:19', NULL);
INSERT INTO `customers` (`customer_id`, `order_number`, `name`, `table_number`, `session_start`, `session_end`) VALUES ('5', 'ORD-00005', NULL, '1', '2026-04-28 05:12:11', NULL);
INSERT INTO `customers` (`customer_id`, `order_number`, `name`, `table_number`, `session_start`, `session_end`) VALUES ('6', 'ORD-00006', NULL, '1', '2026-05-20 20:15:58', NULL);

DROP TABLE IF EXISTS `menu_items`;
CREATE TABLE `menu_items` (
  `menu_item_id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int NOT NULL,
  `item_name` varchar(120) NOT NULL,
  `description` text,
  `price` decimal(10,2) NOT NULL,
  `stock_quantity` int NOT NULL DEFAULT '0',
  `category` varchar(60) NOT NULL DEFAULT 'Uncategorized',
  `is_available` tinyint(1) NOT NULL DEFAULT '1',
  `image_url` varchar(500) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`menu_item_id`),
  KEY `admin_id` (`admin_id`),
  CONSTRAINT `menu_items_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`, `deleted_at`) VALUES ('2', '3', 'S4', 'Coke Float w/ Medium Fries', '159.00', '51', 'Snack', '1', '../uploads/item_3_1777134755.png', '2026-04-26 00:33:24', '2026-05-20 20:15:58', NULL);
INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`, `deleted_at`) VALUES ('8', '3', 'R3', '1-pc Chicken w/ Rice', '120.00', '60', 'Combol Meals', '1', NULL, '2026-04-26 20:54:12', '2026-05-20 20:15:58', NULL);

DROP TABLE IF EXISTS `order_items`;
CREATE TABLE `order_items` (
  `order_item_id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `menu_item_id` int DEFAULT NULL,
  `item_name` varchar(120) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `quantity` int NOT NULL,
  `subtotal` decimal(10,2) NOT NULL,
  PRIMARY KEY (`order_item_id`),
  KEY `order_id` (`order_id`),
  KEY `menu_item_id` (`menu_item_id`),
  CONSTRAINT `order_items_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`order_id`) ON DELETE CASCADE,
  CONSTRAINT `order_items_ibfk_2` FOREIGN KEY (`menu_item_id`) REFERENCES `menu_items` (`menu_item_id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('1', '1', '2', 'S4', '159.00', '2', '318.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('2', '2', '2', 'S4', '159.00', '1', '159.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('3', '2', '8', 'R3', '120.00', '1', '120.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('4', '3', '8', 'R3', '120.00', '2', '240.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('5', '4', '2', 'S4', '159.00', '1', '159.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('6', '4', '8', 'R3', '120.00', '2', '240.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('7', '5', '2', 'S4', '159.00', '3', '477.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('8', '5', '8', 'R3', '120.00', '1', '120.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('9', '6', '2', 'S4', '159.00', '3', '477.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('10', '6', '8', 'R3', '120.00', '2', '240.00');

DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders` (
  `order_id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int NOT NULL,
  `customer_id` int NOT NULL,
  `order_status` enum('Queued','Preparing','Served','Cancelled') NOT NULL DEFAULT 'Queued',
  `total_amount` decimal(10,2) NOT NULL DEFAULT '0.00',
  `queue_number` int NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`order_id`),
  KEY `admin_id` (`admin_id`),
  KEY `customer_id` (`customer_id`),
  CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE CASCADE,
  CONSTRAINT `orders_ibfk_2` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`customer_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`) VALUES ('1', '3', '1', 'Served', '318.00', '1', '2026-04-27 00:03:05');
INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`) VALUES ('2', '3', '2', 'Cancelled', '279.00', '2', '2026-04-27 17:07:50');
INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`) VALUES ('3', '3', '3', 'Served', '240.00', '3', '2026-04-27 17:30:12');
INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`) VALUES ('4', '3', '4', 'Served', '399.00', '4', '2026-04-27 17:31:19');
INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`) VALUES ('5', '3', '5', 'Served', '597.00', '1', '2026-04-28 05:12:11');
INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`) VALUES ('6', '3', '6', 'Served', '717.00', '1', '2026-05-20 20:15:58');

DROP TABLE IF EXISTS `payments`;
CREATE TABLE `payments` (
  `payment_id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `payment_method` enum('Cash','GCash','Credit Card') NOT NULL DEFAULT 'Cash',
  `amount_paid` decimal(10,2) NOT NULL,
  `change_given` decimal(10,2) NOT NULL DEFAULT '0.00',
  `receipt_number` varchar(30) NOT NULL,
  `payment_status` enum('Completed','Pending','Failed') NOT NULL DEFAULT 'Pending',
  `payment_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`payment_id`),
  UNIQUE KEY `order_id` (`order_id`),
  UNIQUE KEY `receipt_number` (`receipt_number`),
  CONSTRAINT `payments_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`order_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('1', '1', 'Cash', '400.00', '82.00', 'RCP-69EE373935417', 'Completed', '2026-04-27 00:03:05');
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('2', '2', 'Cash', '400.00', '121.00', 'RCP-69EF27662671E', 'Failed', '2026-04-27 17:07:50');
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('3', '3', 'Cash', '450.00', '210.00', 'RCP-69EF2CA410750', 'Completed', '2026-04-27 17:30:12');
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('4', '4', 'Cash', '500.00', '101.00', 'RCP-69EF2CE756D19', 'Completed', '2026-04-27 17:31:19');
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('5', '5', 'Cash', '597.00', '0.00', 'RCP-69EFD12B9C61C', 'Completed', '2026-04-28 05:12:11');
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('6', '6', 'Cash', '750.00', '33.00', 'RCP-6A0DA5FE219EA', 'Completed', '2026-05-20 20:15:58');

DROP TABLE IF EXISTS `staff_sessions`;
CREATE TABLE `staff_sessions` (
  `session_id` int NOT NULL AUTO_INCREMENT,
  `staff_id` int NOT NULL,
  `admin_id` int NOT NULL,
  `login_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `logout_at` timestamp NULL DEFAULT NULL,
  `duration_minutes` int DEFAULT NULL,
  PRIMARY KEY (`session_id`),
  KEY `staff_id` (`staff_id`),
  CONSTRAINT `staff_sessions_ibfk_1` FOREIGN KEY (`staff_id`) REFERENCES `staffs` (`staff_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`) VALUES ('1', '6', '3', '2026-05-20 06:30:57', '2026-05-20 06:31:21', '0');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`) VALUES ('2', '6', '3', '2026-05-20 20:15:38', '2026-05-20 20:16:11', '0');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`) VALUES ('3', '5', '3', '2026-05-20 20:17:27', '2026-05-20 20:17:52', '0');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`) VALUES ('4', '6', '3', '2026-05-20 21:28:18', '2026-05-20 21:28:27', '0');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`) VALUES ('5', '6', '3', '2026-05-20 21:29:25', '2026-05-20 21:30:21', '0');

DROP TABLE IF EXISTS `staffs`;
CREATE TABLE `staffs` (
  `staff_id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int NOT NULL,
  `fullname` varchar(100) NOT NULL,
  `role` enum('Cashier','Kitchen','Manager','Waiter','Other') NOT NULL DEFAULT 'Cashier',
  `pin` varchar(255) DEFAULT NULL,
  `status` enum('Active','Inactive') NOT NULL DEFAULT 'Active',
  `shift_start` time DEFAULT NULL,
  `shift_end` time DEFAULT NULL,
  `login_fail_count` int NOT NULL DEFAULT '0',
  `last_fail_at` timestamp NULL DEFAULT NULL,
  `last_login_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `is_online` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`staff_id`),
  KEY `admin_id` (`admin_id`),
  CONSTRAINT `staffs_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`, `is_online`) VALUES ('1', '8', 'Renelle Rose Asis Januyan', 'Cashier', '$2y$12$eVx2e4/dk/zRg5L56lsCZeKDNMNcFxlvzRCv5cO2zlaRC/lbmVELa', 'Active', '13:00:00', '17:00:00', '0', NULL, '2026-05-08 07:07:11', '2026-05-07 11:40:41', '0');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`, `is_online`) VALUES ('2', '3', 'Renelle Rose A. Januyan', 'Cashier', '$2y$12$eUbE5FhVHIBef9xyEkwP6uFGldEr1vglEr9YJKVsNLuH2vS/8BCPe', 'Active', '12:00:00', '18:00:00', '0', NULL, '2026-05-20 05:57:45', '2026-05-08 06:30:40', '0');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`, `is_online`) VALUES ('3', '3', 'miles vales', 'Kitchen', '$2y$12$ZbIwLDUqiCL9MdAklrEccecqAMNHiAHQeC5xlTcp/gubXC7mdbG0q', 'Active', NULL, NULL, '0', NULL, '2026-05-08 09:31:18', '2026-05-08 09:31:03', '0');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`, `is_online`) VALUES ('5', '3', 'rafaelito', 'Kitchen', '$2y$12$eQo0sPYa4aNMOy5/sr7RauUGKQiwqOo9AOPktMH4/Iu7QeZEJNm06', 'Active', '11:00:00', '17:00:00', '0', NULL, '2026-05-20 20:17:27', '2026-05-18 22:09:34', '0');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`, `is_online`) VALUES ('6', '3', 'renelle', 'Cashier', '$2y$12$Nmo6oT1TJ2Jsg8e6tonML.Y2I1nPb51UH1KfEuPQElSFNaMLZHi4S', 'Active', '06:00:00', '12:00:00', '0', NULL, '2026-05-20 21:29:25', '2026-05-20 05:58:59', '0');

DROP TABLE IF EXISTS `system_settings`;
CREATE TABLE `system_settings` (
  `setting_key` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `setting_value` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  PRIMARY KEY (`setting_key`),
  KEY `updated_by` (`updated_by`),
  CONSTRAINT `system_settings_ibfk_1` FOREIGN KEY (`updated_by`) REFERENCES `admins` (`admin_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `system_settings` (`setting_key`, `setting_value`, `updated_at`, `updated_by`) VALUES ('announcement_enabled', '0', '2026-05-21 01:15:37', NULL);
INSERT INTO `system_settings` (`setting_key`, `setting_value`, `updated_at`, `updated_by`) VALUES ('announcement_message', '', '2026-05-21 01:15:37', NULL);
INSERT INTO `system_settings` (`setting_key`, `setting_value`, `updated_at`, `updated_by`) VALUES ('announcement_type', 'info', '2026-05-21 01:15:37', NULL);
INSERT INTO `system_settings` (`setting_key`, `setting_value`, `updated_at`, `updated_by`) VALUES ('maintenance_enabled', '0', '2026-05-21 01:15:37', NULL);
INSERT INTO `system_settings` (`setting_key`, `setting_value`, `updated_at`, `updated_by`) VALUES ('maintenance_end_time', NULL, '2026-05-21 01:15:37', NULL);
INSERT INTO `system_settings` (`setting_key`, `setting_value`, `updated_at`, `updated_by`) VALUES ('maintenance_message', 'We are currently performing scheduled maintenance. We will be back shortly. Thank you for your patience.', '2026-05-21 01:15:37', NULL);

SET FOREIGN_KEY_CHECKS=1;
