-- iPOS Backup | Label: manual | Created: 2026-05-20 21:37:45
-- Generated by iPOS Superadmin Backup & Recovery

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `admin_extended`;
CREATE TABLE `admin_extended` (
  `admin_id` int NOT NULL,
  `age` int DEFAULT NULL,
  `contact_number` varchar(30) DEFAULT NULL,
  `home_address` text,
  `store_address` text,
  `store_location` varchar(100) DEFAULT NULL,
  `store_contact` varchar(30) DEFAULT NULL,
  `bir_permit` varchar(50) DEFAULT NULL,
  `logo_shape` enum('circle','square','rounded') DEFAULT 'circle',
  `logo_url` varchar(500) DEFAULT NULL,
  `profile_photo` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`admin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `admin_extended` (`admin_id`, `age`, `contact_number`, `home_address`, `store_address`, `store_location`, `store_contact`, `bir_permit`, `logo_shape`, `logo_url`, `profile_photo`) VALUES ('9', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle', '../uploads/logo_9_1779259769.png', '../uploads/logo_9_1779259786.png');
INSERT INTO `admin_extended` (`admin_id`, `age`, `contact_number`, `home_address`, `store_address`, `store_location`, `store_contact`, `bir_permit`, `logo_shape`, `logo_url`, `profile_photo`) VALUES ('11', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle', NULL, '../uploads/logo_11_1778835055.png');
INSERT INTO `admin_extended` (`admin_id`, `age`, `contact_number`, `home_address`, `store_address`, `store_location`, `store_contact`, `bir_permit`, `logo_shape`, `logo_url`, `profile_photo`) VALUES ('12', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle', NULL, '../uploads/logo_12_1779191554.png');
INSERT INTO `admin_extended` (`admin_id`, `age`, `contact_number`, `home_address`, `store_address`, `store_location`, `store_contact`, `bir_permit`, `logo_shape`, `logo_url`, `profile_photo`) VALUES ('13', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle', '../uploads/logo_13_1779192592.png', NULL);
INSERT INTO `admin_extended` (`admin_id`, `age`, `contact_number`, `home_address`, `store_address`, `store_location`, `store_contact`, `bir_permit`, `logo_shape`, `logo_url`, `profile_photo`) VALUES ('16', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle', '../uploads/logo_16_1779304825.png', '../uploads/logo_16_1779304844.png');

DROP TABLE IF EXISTS `admin_sessions`;
CREATE TABLE `admin_sessions` (
  `session_id` varchar(255) NOT NULL,
  `admin_id` int NOT NULL,
  `login_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `logout_time` timestamp NULL DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`session_id`),
  KEY `admin_id` (`admin_id`),
  CONSTRAINT `admin_sessions_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `admin_sessions` (`session_id`, `admin_id`, `login_time`, `logout_time`, `is_active`) VALUES ('12f6c06963744194ca9f58c477a38084', '16', '2026-05-21 03:19:53', NULL, '0');
INSERT INTO `admin_sessions` (`session_id`, `admin_id`, `login_time`, `logout_time`, `is_active`) VALUES ('2618b723ac590ea72de8a49845a28585', '13', '2026-05-20 12:00:49', NULL, '0');
INSERT INTO `admin_sessions` (`session_id`, `admin_id`, `login_time`, `logout_time`, `is_active`) VALUES ('412593405e1d2c4945494c60520093d7', '9', '2026-05-21 05:31:19', NULL, '0');
INSERT INTO `admin_sessions` (`session_id`, `admin_id`, `login_time`, `logout_time`, `is_active`) VALUES ('618bbad2a8ac99b507945fa2e36c1eba', '1', '2026-05-21 05:32:18', NULL, '1');
INSERT INTO `admin_sessions` (`session_id`, `admin_id`, `login_time`, `logout_time`, `is_active`) VALUES ('ac8a9705ff3d6248e4c48745acecfc97', '3', '2026-04-30 06:17:42', NULL, '1');
INSERT INTO `admin_sessions` (`session_id`, `admin_id`, `login_time`, `logout_time`, `is_active`) VALUES ('b54047102b315779e30d51a76a1914e1', '6', '2026-05-08 09:20:42', NULL, '1');
INSERT INTO `admin_sessions` (`session_id`, `admin_id`, `login_time`, `logout_time`, `is_active`) VALUES ('ec897a26585fb7069b9e2760d6b9b2fe', '17', '2026-05-21 05:11:44', NULL, '0');

DROP TABLE IF EXISTS `admins`;
CREATE TABLE `admins` (
  `admin_id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `fullname` varchar(100) NOT NULL,
  `fastfood_name` varchar(100) DEFAULT NULL,
  `role` enum('superadmin','owner') DEFAULT 'owner',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login` timestamp NULL DEFAULT NULL,
  `phone_number` varchar(20) DEFAULT NULL,
  `business_type` varchar(50) DEFAULT NULL,
  `tin_number` varchar(30) DEFAULT NULL,
  `dti_sec_number` varchar(50) DEFAULT NULL,
  `business_permit` varchar(50) DEFAULT NULL,
  `address` text,
  `city` varchar(100) DEFAULT NULL,
  `province` varchar(100) DEFAULT NULL,
  `zip_code` varchar(10) DEFAULT NULL,
  `logo_url` varchar(255) DEFAULT NULL,
  `logo_shape` varchar(20) DEFAULT 'circle',
  `dashboard_pin` varchar(255) DEFAULT NULL,
  `theme_data` text,
  PRIMARY KEY (`admin_id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`, `dashboard_pin`, `theme_data`) VALUES ('1', 'superadmin', 'ipossuperadmin@gmail.com', '$2y$12$s1jhaekLFC/MqgQf6l6LvO1jLqIyS5mlWZpLxGyejtlFTtWV2HzuS', 'System Administrator', NULL, 'superadmin', '2026-04-27 09:15:03', '2026-05-21 05:32:18', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle', NULL, NULL);
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`, `dashboard_pin`, `theme_data`) VALUES ('3', 'kathy', 'kath@gamil.com', '$2y$12$8xrVefb3aNY2Oa994Q0VLeHdeig6Zsvz0aHTXFf6voSqTZQgCFnWC', 'Katherine Lorejas', 'McDo', 'owner', '2026-04-30 06:01:57', '2026-04-30 06:17:42', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle', NULL, NULL);
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`, `dashboard_pin`, `theme_data`) VALUES ('6', 'steven', 'epis@gmail.com', '$2y$12$Annyj0/Mx9/T0JiASKP/0uqYgEHp.uyEc3M/051HAAI2Imqk2GM3G', 'steven Epis', 'AratNa', 'owner', '2026-05-08 09:01:22', '2026-05-08 09:20:42', '0369855145223', 'Catering', '1236545', '', '', '', '', '', '6607', 'dashboard/uploads/logos/logo_1778202081_69fd35e18f4c4.png', 'circle', NULL, NULL);
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`, `dashboard_pin`, `theme_data`) VALUES ('8', 'anarose', 'anaroses@gmail.com', '$2y$12$ZMYHxJ839l3NDgogchP.Xe6cVLi5ThdavN/52gbzlKtcutZGxWJVm', 'Ana Rose Sumayang', 'AratNa', 'owner', '2026-05-10 15:36:15', '2026-05-10 21:47:23', '09512365422', 'Restaurant', '123-654-788-855', '12345678-9012', 'BP-2024-001234', 'Barangay Tubaon, Purok 3', 'Silago', 'Southern Leyte', '6607', NULL, 'circle', NULL, NULL);
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`, `dashboard_pin`, `theme_data`) VALUES ('9', 'sabel', 'sabel@gmail.com', '$2y$12$Q2jhpy6/U4itC4/aSbNfKO11HoWcWoEdjxHjcUFcVMc.V21qEwf6a', 'Joshenabelle Degorio', 'SabelPH', 'owner', '2026-05-10 21:51:24', '2026-05-21 05:31:19', '09876554321', 'Restaurant', '472-349-753-683', '372462578', '324237523', 'Barangay Tubaon', 'Sogod', 'Southern Leyte', '6606', 'dashboard/uploads/logos/logo_1778421083_6a008d5bafc94.png', 'square', '$2y$12$1ED5oV1JemYUv.vXKOwb..moQpgc2JuNW29MNxDyZd9gTATllwcFu', NULL);
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`, `dashboard_pin`, `theme_data`) VALUES ('10', 'miles', 'vales@gmail.com', '$2y$12$RRaAI66on8w4JNXciu6M7OqnNh99Ao1Tg/x6vxdmusB9tAbIQNCJy', 'Miles', 'Tamis', 'owner', '2026-05-12 10:54:32', '2026-05-12 10:54:49', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle', '$2y$12$Yh5CqjWm3OT5rS54NV2iC.fKEluJSe8MZh7mSqW2q0uu7hq4k/uHu', NULL);
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`, `dashboard_pin`, `theme_data`) VALUES ('11', 'rosemarie', 'rose@gmail.com', '$2y$12$sk2A9Jjd/EKAC0ya3N5l9OSsFO4OLQfANyqvZp2Mhx3H47IAKFnSO', 'Rosemarie Dagandanan', 'BuLikit', 'owner', '2026-05-15 16:49:46', '2026-05-15 20:42:10', '09632156245', 'Restaurant', '789-654-123-644', '09632154', '123654855', 'Tubaon', 'Rizal', 'Cagayan', '6632', 'dashboard/uploads/logos/logo_1778834985_6a06de2939db4.png', 'circle', '$2y$12$FXmDPr0fynaCoqfVD4CrXeHTMdAeJ7.fkpvRM0boA6KHozRNYpzQ.', '{\"sidebarBg\":\"#400720\",\"accent\":\"#BE185D\",\"accentDark\":\"#5C0A2E\",\"bodyBg\":\"#FDF2F8\",\"text\":\"#1a0010\",\"accentLight\":\"#FDF2F8\",\"borderColor\":\"#e7dae0\",\"textSec\":\"#9d6c82\"}');
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`, `dashboard_pin`, `theme_data`) VALUES ('12', 'bewbew', 'bew@gmail.com', '$2y$12$l6EWdH2poQO9oldcyNk50uBgQ4tnK3ftJ//zP8yg1IWvhwFcvjCGm', 'Ana Rose Sumayang', 'MangInasal', 'owner', '2026-05-19 19:50:46', '2026-05-19 19:51:57', '', '', '000-000-000-000', 'lgu-12345', 'bp-2024-12345', 'Barangay Tuba-on, Awo', 'Silago', 'Southern Leyte', '1234', 'dashboard/uploads/logos/logo_1779191445_6a0c4e95b8975.png', 'rounded', '$2y$12$u.AXaFLioQ6UCEOrAy.dM.A1X75rAckgJT4WCDOBiDg/wfGgi1.Ym', NULL);
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`, `dashboard_pin`, `theme_data`) VALUES ('13', 'renel', 'renel@gmail.com', '$2y$12$xbrFolh9atOiSDfWAoARJO3846i/rYdNsi4em0.Roe6/A/tqCbbQ2', 'Renelle Rose Januyan', 'Renel\'sCafe', 'owner', '2026-05-19 20:09:05', '2026-05-20 12:00:49', '09632156445', 'Fast Food', '993-788-384-637', 'lgui-12345', 'bp-2024-123456', 'Barangay Tuba-on, Awo ', 'Padre Burgos', 'Southern Leyte', '1452', NULL, 'circle', '$2y$12$hD57r8u3KsO6LHTz.Nslq.N52..rmUEP3TKGXEkiD4y9SqkhJTg06', NULL);
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`, `dashboard_pin`, `theme_data`) VALUES ('14', 'rosmar', 'rosesd@gmail.com', '$2y$12$cFNa.QDPi3HkhEb8J0G36usH5Mye/jCXaxMup6/km7GtF0TXvo.me', 'Rosemarie Dagandanan', 'Roses', 'owner', '2026-05-19 20:13:48', '2026-05-19 20:14:08', '09632154885', 'Fast Food', '023-654-422-255', 'lgn-12345', 'bp-8902-12283', 'Barangay Tuba-on, Awo', 'Silago', 'Southern Leyte', '2020', 'dashboard/uploads/logos/logo_1779192828_6a0c53fc2cf09.png', 'circle', NULL, NULL);
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`, `dashboard_pin`, `theme_data`) VALUES ('15', '123456', 'bebeko@gmail.com', '$2y$12$0cV2z9N/77hvjliCzgba5u0tak1IoYRvVqD44ox7mmFqw3sP9uPZW', 'Anarose Bebe', 'bebeko', 'owner', '2026-05-19 20:19:29', '2026-05-19 20:19:43', '09632548665', 'Fast Food', '929-274-856-387', 'u2y347234', '4263yrb374', 'Barangay Tuba-on, Awo', 'Padre Burgos', 'Southern Leyte', '1020', 'dashboard/uploads/logos/logo_1779193168_6a0c5550cc4dc.png', 'circle', NULL, NULL);
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`, `dashboard_pin`, `theme_data`) VALUES ('16', 'biww', 'bewbewwwww@gmail.com', '$2y$12$BNUuRzu0B0MvsW9e/dCqWu3x54LJWUgxgJW9l6E1tCFxrwhsi0A5S', 'Babie Miles Vales', 'BahogB', 'owner', '2026-05-21 03:19:43', '2026-05-21 03:19:53', '09654236522', 'Fast Food', '123-654-789-654', 'lgu-123456', 'bp-0987-90885', 'Barangay Sta. Maria, bff', 'Padre Burgos', 'Southern Leyte', '1020', NULL, 'circle', '$2y$12$glleIcXQBGZqYi/o/gflMeczLTAuroKrxenEDKYkHOHbxJQ8dMbQS', NULL);
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `phone_number`, `business_type`, `tin_number`, `dti_sec_number`, `business_permit`, `address`, `city`, `province`, `zip_code`, `logo_url`, `logo_shape`, `dashboard_pin`, `theme_data`) VALUES ('17', 'kathy101', 'kathirin@gmail.com', '$2y$12$QCbko0GRnHZ8Q03Bpko2w.r0/t.Q8I0bbF7kyi.q.Gk6WsndNiDzW', 'Kati Rine', 'kathy', 'owner', '2026-05-21 03:42:16', '2026-05-21 05:11:44', '09542368752', 'Fast Food', '284-723-847-524', 'byt-098324', 'br-73298-23874', 'hgdfebf', 'Obando', 'Bulacan', '5445', 'dashboard/uploads/logos/logo_1779306136_6a0e0e981dd78.png', 'square', '$2y$12$fByLSHoCC7lPdESNBH2nc.3nQl8IxjOVd1Opeg8.4j0iJTwIDLsuK', NULL);

DROP TABLE IF EXISTS `carts`;
CREATE TABLE `carts` (
  `cart_id` int NOT NULL AUTO_INCREMENT,
  `customer_id` int NOT NULL,
  `menu_item_id` int NOT NULL,
  `quantity` int NOT NULL DEFAULT '1',
  `subtotal` decimal(10,2) NOT NULL DEFAULT '0.00',
  `date_added` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cart_id`),
  KEY `customer_id` (`customer_id`),
  KEY `menu_item_id` (`menu_item_id`),
  CONSTRAINT `carts_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`customer_id`) ON DELETE CASCADE,
  CONSTRAINT `carts_ibfk_2` FOREIGN KEY (`menu_item_id`) REFERENCES `menu_items` (`menu_item_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `customers`;
CREATE TABLE `customers` (
  `customer_id` int NOT NULL AUTO_INCREMENT,
  `order_number` varchar(20) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `table_number` varchar(20) DEFAULT NULL,
  `session_start` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `session_end` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `customers` (`customer_id`, `order_number`, `name`, `table_number`, `session_start`, `session_end`) VALUES ('1', 'ORD-00001', NULL, '1', '2026-05-19 17:33:49', NULL);
INSERT INTO `customers` (`customer_id`, `order_number`, `name`, `table_number`, `session_start`, `session_end`) VALUES ('2', 'ORD-00002', NULL, '2', '2026-05-19 17:52:17', NULL);
INSERT INTO `customers` (`customer_id`, `order_number`, `name`, `table_number`, `session_start`, `session_end`) VALUES ('3', 'ORD-00003', NULL, '3', '2026-05-19 17:52:48', NULL);
INSERT INTO `customers` (`customer_id`, `order_number`, `name`, `table_number`, `session_start`, `session_end`) VALUES ('4', 'ORD-00004', NULL, '4', '2026-05-19 17:53:10', NULL);
INSERT INTO `customers` (`customer_id`, `order_number`, `name`, `table_number`, `session_start`, `session_end`) VALUES ('5', 'ORD-00005', NULL, '5', '2026-05-19 17:56:58', NULL);
INSERT INTO `customers` (`customer_id`, `order_number`, `name`, `table_number`, `session_start`, `session_end`) VALUES ('6', 'ORD-00006', NULL, '6', '2026-05-19 18:41:32', NULL);
INSERT INTO `customers` (`customer_id`, `order_number`, `name`, `table_number`, `session_start`, `session_end`) VALUES ('7', 'ORD-00007', NULL, '7', '2026-05-19 22:56:59', NULL);

DROP TABLE IF EXISTS `menu_items`;
CREATE TABLE `menu_items` (
  `menu_item_id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int NOT NULL,
  `item_name` varchar(120) NOT NULL,
  `description` text,
  `price` decimal(10,2) NOT NULL,
  `stock_quantity` int NOT NULL DEFAULT '0',
  `category` varchar(60) NOT NULL DEFAULT 'Uncategorized',
  `is_available` tinyint(1) NOT NULL DEFAULT '1',
  `image_url` varchar(500) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`menu_item_id`),
  KEY `admin_id` (`admin_id`),
  CONSTRAINT `menu_items_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('1', '3', 'Hinga', 'portable inhaler', '49.00', '100', 'inhaler', '1', '../uploads/item_3_1777501193.png', '2026-04-30 06:20:49', '2026-04-30 06:20:49');
INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('2', '9', 'burger', 'bahuuu', '20.00', '25', 'basta', '1', '../uploads/item_9_1779183055.png', '2026-05-19 17:31:22', '2026-05-19 22:56:59');
INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('3', '9', 'frieskamuna', 'favorite ko to', '50.00', '8', 'Junkards', '1', '../uploads/item_9_1779183093.png', '2026-05-19 17:32:05', '2026-05-19 17:56:58');
INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('4', '17', 'hays', 'bjg', '100.00', '12', 'burger', '1', '../uploads/item_17_1779310732.jpg', '2026-05-21 04:59:14', '2026-05-21 04:59:14');
INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('5', '17', 'hgf', 'fghd', '544.00', '452', 'fhyfyuf', '1', NULL, '2026-05-21 04:59:44', '2026-05-21 04:59:44');

DROP TABLE IF EXISTS `order_items`;
CREATE TABLE `order_items` (
  `order_item_id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `menu_item_id` int DEFAULT NULL,
  `item_name` varchar(120) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `quantity` int NOT NULL,
  `subtotal` decimal(10,2) NOT NULL,
  PRIMARY KEY (`order_item_id`),
  KEY `order_id` (`order_id`),
  KEY `menu_item_id` (`menu_item_id`),
  CONSTRAINT `order_items_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`order_id`) ON DELETE CASCADE,
  CONSTRAINT `order_items_ibfk_2` FOREIGN KEY (`menu_item_id`) REFERENCES `menu_items` (`menu_item_id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('1', '1', '2', 'burger', '20.00', '1', '20.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('2', '1', '3', 'frieskamuna', '50.00', '1', '50.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('3', '2', '2', 'burger', '20.00', '2', '40.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('4', '2', '3', 'frieskamuna', '50.00', '2', '100.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('5', '3', '3', 'frieskamuna', '50.00', '2', '100.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('6', '4', '3', 'frieskamuna', '50.00', '1', '50.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('7', '5', '3', 'frieskamuna', '50.00', '1', '50.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('8', '6', '2', 'burger', '20.00', '1', '20.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('9', '7', '2', 'burger', '20.00', '1', '20.00');

DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders` (
  `order_id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int NOT NULL,
  `customer_id` int NOT NULL,
  `order_status` enum('Queued','Preparing','Served','Cancelled') NOT NULL DEFAULT 'Queued',
  `total_amount` decimal(10,2) NOT NULL DEFAULT '0.00',
  `queue_number` int NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`order_id`),
  KEY `admin_id` (`admin_id`),
  KEY `customer_id` (`customer_id`),
  CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE CASCADE,
  CONSTRAINT `orders_ibfk_2` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`customer_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`) VALUES ('1', '9', '1', 'Served', '70.00', '1', '2026-05-19 17:33:49');
INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`) VALUES ('2', '9', '2', 'Preparing', '140.00', '2', '2026-05-19 17:52:17');
INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`) VALUES ('3', '9', '3', 'Queued', '100.00', '3', '2026-05-19 17:52:48');
INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`) VALUES ('4', '9', '4', 'Queued', '50.00', '4', '2026-05-19 17:53:10');
INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`) VALUES ('5', '9', '5', 'Queued', '50.00', '5', '2026-05-19 17:56:58');
INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`) VALUES ('6', '9', '6', 'Queued', '20.00', '6', '2026-05-19 18:41:32');
INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`) VALUES ('7', '9', '7', 'Queued', '20.00', '7', '2026-05-19 22:56:59');

DROP TABLE IF EXISTS `payments`;
CREATE TABLE `payments` (
  `payment_id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `payment_method` enum('Cash','GCash','Credit Card') NOT NULL DEFAULT 'Cash',
  `amount_paid` decimal(10,2) NOT NULL,
  `change_given` decimal(10,2) NOT NULL DEFAULT '0.00',
  `receipt_number` varchar(30) NOT NULL,
  `payment_status` enum('Completed','Pending','Failed') NOT NULL DEFAULT 'Pending',
  `payment_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`payment_id`),
  UNIQUE KEY `order_id` (`order_id`),
  UNIQUE KEY `receipt_number` (`receipt_number`),
  CONSTRAINT `payments_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`order_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('1', '1', 'Cash', '100.00', '30.00', 'RCP-6A0C2E7DC3B99', 'Completed', '2026-05-19 17:33:49');
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('2', '2', 'Cash', '1000.00', '860.00', 'RCP-6A0C32D1DAD4F', 'Completed', '2026-05-19 17:52:17');
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('3', '3', 'Cash', '140.00', '40.00', 'RCP-6A0C32F02D7CC', 'Completed', '2026-05-19 17:52:48');
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('4', '4', 'Cash', '100.00', '50.00', 'RCP-6A0C3306F0270', 'Completed', '2026-05-19 17:53:10');
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('5', '5', 'Cash', '50.00', '0.00', 'RCP-6A0C33EA4B37A', 'Completed', '2026-05-19 17:56:58');
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('6', '6', 'Cash', '20.00', '0.00', 'RCP-6A0C3E5C87920', 'Completed', '2026-05-19 18:41:32');
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('7', '7', 'Cash', '100.00', '80.00', 'RCP-6A0C7A3BE68F2', 'Completed', '2026-05-19 22:56:59');

DROP TABLE IF EXISTS `staff_sessions`;
CREATE TABLE `staff_sessions` (
  `session_id` int NOT NULL AUTO_INCREMENT,
  `staff_id` int NOT NULL,
  `admin_id` int NOT NULL,
  `login_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `logout_at` timestamp NULL DEFAULT NULL,
  `duration_minutes` int DEFAULT NULL,
  `late_minutes` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`session_id`),
  KEY `staff_id` (`staff_id`),
  CONSTRAINT `staff_sessions_ibfk_1` FOREIGN KEY (`staff_id`) REFERENCES `staffs` (`staff_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`, `late_minutes`) VALUES ('3', '7', '9', '2026-05-20 17:25:16', '2026-05-20 17:27:41', '2', '0');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`, `late_minutes`) VALUES ('4', '6', '9', '2026-05-20 17:50:35', '2026-05-20 17:50:52', '0', '0');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`, `late_minutes`) VALUES ('5', '7', '9', '2026-05-20 17:51:45', '2026-05-20 17:51:55', '0', '0');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`, `late_minutes`) VALUES ('8', '9', '9', '2026-05-20 18:13:28', '2026-05-20 18:13:38', '0', '13');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`, `late_minutes`) VALUES ('9', '6', '9', '2026-05-20 18:13:57', '2026-05-20 18:14:07', '0', '193');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`, `late_minutes`) VALUES ('10', '9', '9', '2026-05-20 18:16:53', '2026-05-20 18:16:58', '0', '16');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`, `late_minutes`) VALUES ('11', '10', '9', '2026-05-20 18:22:05', '2026-05-20 18:22:15', '0', '22');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`, `late_minutes`) VALUES ('12', '10', '9', '2026-05-20 18:33:53', '2026-05-20 18:34:00', '0', '33');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`, `late_minutes`) VALUES ('13', '10', '9', '2026-05-20 18:35:57', '2026-05-20 18:36:06', '0', '35');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`, `late_minutes`) VALUES ('14', '11', '9', '2026-05-20 22:45:13', '2026-05-20 22:45:20', '0', '0');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`, `late_minutes`) VALUES ('15', '12', '9', '2026-05-20 23:26:42', '2026-05-20 23:27:17', '0', '6');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`, `late_minutes`) VALUES ('16', '12', '9', '2026-05-21 00:40:13', '2026-05-21 00:43:46', '3', '0');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`, `late_minutes`) VALUES ('17', '13', '9', '2026-05-21 00:50:33', '2026-05-21 01:07:03', '16', '0');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`, `late_minutes`) VALUES ('18', '14', '17', '2026-05-21 04:03:38', '2026-05-21 04:16:55', '13', '3');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`, `late_minutes`) VALUES ('19', '15', '17', '2026-05-21 04:18:49', '2026-05-21 04:18:59', '0', '8');
INSERT INTO `staff_sessions` (`session_id`, `staff_id`, `admin_id`, `login_at`, `logout_at`, `duration_minutes`, `late_minutes`) VALUES ('20', '15', '17', '2026-05-21 04:23:05', '2026-05-21 04:23:11', '0', '13');

DROP TABLE IF EXISTS `staffs`;
CREATE TABLE `staffs` (
  `staff_id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int NOT NULL,
  `fullname` varchar(100) NOT NULL,
  `role` enum('Cashier','Kitchen') NOT NULL DEFAULT 'Cashier',
  `pin` varchar(255) DEFAULT NULL,
  `status` enum('Active','Inactive') NOT NULL DEFAULT 'Active',
  `shift_start` time DEFAULT NULL,
  `shift_end` time DEFAULT NULL,
  `login_fail_count` int NOT NULL DEFAULT '0',
  `last_fail_at` timestamp NULL DEFAULT NULL,
  `last_login_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `is_online` tinyint(1) NOT NULL DEFAULT '0',
  `employment_type` enum('Full-time','Part-time') NOT NULL DEFAULT 'Full-time',
  PRIMARY KEY (`staff_id`),
  KEY `admin_id` (`admin_id`),
  CONSTRAINT `staffs_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`, `is_online`, `employment_type`) VALUES ('1', '11', 'Babie Miles', 'Cashier', '$2y$12$rPr3GqWL2cjmMX9oy6UDZOaXLrQ/qvad61Ubkm6AcGWCw9Lpbkx1a', 'Active', '07:00:00', '12:00:00', '0', NULL, '2026-05-15 20:53:05', '2026-05-15 16:59:41', '0', 'Full-time');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`, `is_online`, `employment_type`) VALUES ('4', '12', 'Renelle RoseJanuyan', 'Kitchen', '$2y$12$utMXUOmPN0w1LEqUlZwRhelJlWnzxw2ApZCweo8LtR5OYrays9av.', 'Active', '10:30:00', '22:30:00', '0', NULL, NULL, '2026-05-19 19:53:32', '0', 'Full-time');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`, `is_online`, `employment_type`) VALUES ('5', '9', 'Jay Enrique', 'Kitchen', '$2y$12$Dxqi9kYL/iVTD4Y4jAKUYeFIBkKjirek1e29Gu5Ac4QhteUnCo9zq', 'Active', '10:30:00', '22:30:00', '0', NULL, NULL, '2026-05-20 11:36:34', '0', 'Full-time');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`, `is_online`, `employment_type`) VALUES ('6', '9', 'Bewbew Gwapa', 'Kitchen', '$2y$12$EnSxJNDoYDnKOoUaXq8Cee.NKShtjqwaTgEmxBSWrQxanxIG.kxpu', 'Active', '15:00:00', '17:00:00', '0', NULL, '2026-05-20 18:13:57', '2026-05-20 15:50:22', '0', 'Full-time');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`, `is_online`, `employment_type`) VALUES ('7', '9', 'Kath', 'Cashier', '$2y$12$Z98SaE79Dxmwx4QqEb8tY.LIdOFX/MSGYgBQXIwdhlfNzNbsuzIGC', 'Active', '16:00:00', '17:00:00', '0', NULL, '2026-05-20 17:51:45', '2026-05-20 15:52:37', '0', 'Full-time');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`, `is_online`, `employment_type`) VALUES ('8', '9', 'Ana Rose Sumayang', 'Cashier', '$2y$12$Iph0WgW.4mjlA25wOQVMfuMuBwksVGZKC1vQ1fyLqr1wUcEdGpmCi', 'Active', '17:00:00', '19:00:00', '0', NULL, NULL, '2026-05-20 17:59:29', '0', 'Full-time');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`, `is_online`, `employment_type`) VALUES ('9', '9', 'Renel Maot', 'Kitchen', '$2y$12$xXXAGgMrh4tinzhyTr3WVOKgaapZDFNh1KMVQ/7zzw4I4HFSR5xXe', 'Active', '18:00:00', '19:00:00', '0', NULL, '2026-05-20 18:16:53', '2026-05-20 18:03:20', '0', 'Full-time');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`, `is_online`, `employment_type`) VALUES ('10', '9', 'Jonel Ok', 'Cashier', '$2y$12$pFIdTEaWoNWE5./yzJ9nZuMP6B098SNAzWQCVDEQAWTEFTFgTT6OW', 'Active', '18:00:00', '07:00:00', '0', NULL, '2026-05-20 18:35:57', '2026-05-20 18:19:21', '0', 'Full-time');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`, `is_online`, `employment_type`) VALUES ('11', '9', 'Baby Ko', 'Cashier', '$2y$12$4GjQwwNMXPGHmzRoA2pY.e6.K9bxCL4rlOpaqqQUQmLzaUyOmIv0i', 'Active', '22:45:00', '01:30:00', '0', NULL, '2026-05-20 22:45:13', '2026-05-20 22:43:24', '0', 'Full-time');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`, `is_online`, `employment_type`) VALUES ('12', '9', 'Babie Moko', 'Kitchen', '$2y$12$zs7g1C0pdeqblAhk/CxCYerXAZEaF.5nYYbnq5HXudY8Cq/t7.eeq', 'Active', '23:20:00', '01:30:00', '0', NULL, '2026-05-21 00:40:13', '2026-05-20 23:22:30', '0', 'Part-time');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`, `is_online`, `employment_type`) VALUES ('13', '9', 'Kathy Rine', 'Cashier', '$2y$12$j6N/PFU5dYCEfEA0UjSFj.n97E3cHxg4DDhOZtH.VYzXVW65QfeWy', 'Active', '00:50:00', '02:30:00', '0', NULL, '2026-05-21 00:50:33', '2026-05-21 00:47:40', '0', 'Part-time');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`, `is_online`, `employment_type`) VALUES ('14', '17', 'Renelle Rose Januyan', 'Cashier', '$2y$12$MQGJUwdCGmplVfnQ/QZI2OMDE/DMI1qtJKAWJBX8W171eabjVH1HK', 'Active', '05:00:00', '05:00:00', '0', NULL, '2026-05-21 04:03:38', '2026-05-21 03:59:28', '0', 'Full-time');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`, `is_online`, `employment_type`) VALUES ('15', '17', 'Babie Miles Vales', 'Kitchen', '$2y$12$oIlIFaO75KFjCFMxg5ydf.rqRElserzDEyCH3qERFt7Njz6GhUk9u', 'Active', '04:10:00', '06:00:00', '0', NULL, '2026-05-21 04:23:05', '2026-05-21 04:02:42', '0', 'Full-time');

DROP TABLE IF EXISTS `system_settings`;
CREATE TABLE `system_settings` (
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  PRIMARY KEY (`setting_key`),
  KEY `updated_by` (`updated_by`),
  CONSTRAINT `system_settings_ibfk_1` FOREIGN KEY (`updated_by`) REFERENCES `admins` (`admin_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `system_settings` (`setting_key`, `setting_value`, `updated_at`, `updated_by`) VALUES ('announcement_enabled', '0', '2026-05-21 03:00:55', NULL);
INSERT INTO `system_settings` (`setting_key`, `setting_value`, `updated_at`, `updated_by`) VALUES ('announcement_message', '', '2026-05-21 03:00:55', NULL);
INSERT INTO `system_settings` (`setting_key`, `setting_value`, `updated_at`, `updated_by`) VALUES ('announcement_type', 'info', '2026-05-21 03:00:55', NULL);
INSERT INTO `system_settings` (`setting_key`, `setting_value`, `updated_at`, `updated_by`) VALUES ('maintenance_enabled', '0', '2026-05-21 03:00:55', NULL);
INSERT INTO `system_settings` (`setting_key`, `setting_value`, `updated_at`, `updated_by`) VALUES ('maintenance_end_time', NULL, '2026-05-21 03:00:55', NULL);
INSERT INTO `system_settings` (`setting_key`, `setting_value`, `updated_at`, `updated_by`) VALUES ('maintenance_message', 'We are currently performing scheduled maintenance. We will be back shortly. Thank you for your patience.', '2026-05-21 03:00:55', NULL);

SET FOREIGN_KEY_CHECKS=1;
