-- iPOS Backup | Label: new_user | Created: 2026-05-17 14:36:21
-- Generated by iPOS Superadmin Backup & Recovery

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `admin_sessions`;
CREATE TABLE `admin_sessions` (
  `session_id` varchar(255) NOT NULL,
  `admin_id` int NOT NULL,
  `login_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `logout_time` timestamp NULL DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`session_id`),
  KEY `admin_id` (`admin_id`),
  CONSTRAINT `admin_sessions_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `admin_sessions` (`session_id`, `admin_id`, `login_time`, `logout_time`, `is_active`) VALUES ('ebc8f5ffa8569e4074f59afbb0e7657f', '1', '2026-05-17 14:35:51', NULL, '1');

DROP TABLE IF EXISTS `admins`;
CREATE TABLE `admins` (
  `admin_id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `fullname` varchar(100) NOT NULL,
  `fastfood_name` varchar(100) DEFAULT NULL,
  `role` enum('superadmin','owner') DEFAULT 'owner',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login` timestamp NULL DEFAULT NULL,
  `max_devices` int DEFAULT '1',
  `dashboard_pin` varchar(255) DEFAULT NULL,
  `phone_number` varchar(20) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `municipality` varchar(100) DEFAULT NULL,
  `province` varchar(100) DEFAULT NULL,
  `zip_code` varchar(10) DEFAULT NULL,
  `business_permit` varchar(100) DEFAULT NULL,
  `logo` varchar(255) DEFAULT NULL,
  `theme` varchar(50) DEFAULT NULL,
  `business_type` varchar(100) DEFAULT NULL,
  `dti_sec_number` varchar(100) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `logo_url` varchar(255) DEFAULT NULL,
  `logo_shape` varchar(50) DEFAULT 'circle',
  `tin_number` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`admin_id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `max_devices`, `dashboard_pin`, `phone_number`, `address`, `municipality`, `province`, `zip_code`, `business_permit`, `logo`, `theme`, `business_type`, `dti_sec_number`, `city`, `logo_url`, `logo_shape`, `tin_number`) VALUES ('1', 'superAdmin', 'ipossuperadmin@gmail.com', '$2y$12$s1jhaekLFC/MqgQf6l6LvO1jLqIyS5mlWZpLxGyejtlFTtWV2HzuS', 'System Administrator', NULL, 'superadmin', '2026-05-14 21:45:21', '2026-05-17 14:35:51', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'circle', NULL);
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `max_devices`, `dashboard_pin`, `phone_number`, `address`, `municipality`, `province`, `zip_code`, `business_permit`, `logo`, `theme`, `business_type`, `dti_sec_number`, `city`, `logo_url`, `logo_shape`, `tin_number`) VALUES ('3', 'uzumaki', 'btsbighitarmymoa@gmail.com', '$2y$12$1t9r/DW/D/cClb74S6bFzO75U5ifg8m4y.3JFQPNso8128AovU8K2', 'Naruto Uzumaki', 'uzumaki ramen', 'owner', '2026-05-15 14:12:26', '2026-05-15 14:12:32', '1', '$2y$12$C8M.NyXl2Vu4plmw29DSg.760mQqIFyMbeRHEXLH54aJHd9pg4xjW', '09357012999', 'Tokyo Japan', NULL, '', '2134', '', NULL, NULL, 'Restaurant', '', 'Tokyo', NULL, 'circle', '123-123-3');
INSERT INTO `admins` (`admin_id`, `username`, `email`, `password`, `fullname`, `fastfood_name`, `role`, `created_at`, `last_login`, `max_devices`, `dashboard_pin`, `phone_number`, `address`, `municipality`, `province`, `zip_code`, `business_permit`, `logo`, `theme`, `business_type`, `dti_sec_number`, `city`, `logo_url`, `logo_shape`, `tin_number`) VALUES ('4', 'ninagraceteroyang@gmail.com', 'ninagraceteroyang@gmail.com', '$2y$12$59B75kcN9TegpQuUaZyLku2fhr3trEwBprLLH//EY.6M01qvwQ25.', 'kath', 'cafees', 'owner', '2026-05-17 14:29:25', '2026-05-17 14:29:33', '1', NULL, '0912345346', 'Mahaplag', NULL, 'Leyte', '2134', '', NULL, NULL, 'Cafe', '', 'Mahaplag', NULL, 'circle', '123-123-3');

DROP TABLE IF EXISTS `audit_log`;
CREATE TABLE `audit_log` (
  `log_id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int DEFAULT NULL,
  `actor_name` varchar(100) NOT NULL DEFAULT '',
  `action` varchar(80) NOT NULL,
  `target_type` varchar(50) DEFAULT NULL,
  `target_id` int DEFAULT NULL,
  `target_label` varchar(200) DEFAULT NULL,
  `detail` text,
  `ip_address` varchar(45) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  KEY `admin_id` (`admin_id`),
  CONSTRAINT `audit_log_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('1', '1', 'superAdmin', 'superadmin_credentials_updated', 'superadmin', '1', 'superAdmin', 'Username and email updated', '::1', '2026-05-15 11:35:15');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('2', '1', 'superAdmin', 'backup_created', 'backup', NULL, 'backup_manual_20260515_140547.sql', 'Backup label: manual, tables: 10', '::1', '2026-05-15 14:05:47');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('3', '1', 'superAdmin', 'superadmin_logout', 'superadmin', '1', 'superAdmin', 'Superadmin logged out', '::1', '2026-05-15 14:07:55');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('4', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-15 14:08:08');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('5', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-15 14:08:09');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('6', '1', 'superAdmin', 'superadmin_logout', 'superadmin', '1', 'superAdmin', 'Superadmin logged out', '::1', '2026-05-15 14:08:20');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('7', NULL, 'superadmin', 'owner_created', 'owner', NULL, 'uzumaki', 'New owner registered: uzumaki (uzumaki ramen)', '::1', '2026-05-15 14:12:27');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('8', NULL, 'uzumaki', 'failed_login_attempt', NULL, NULL, 'uzumaki', 'Failed login attempt for username: uzumaki', '::1', '2026-05-15 14:16:28');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('9', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-15 14:16:38');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('10', '1', 'superAdmin', 'owner_deleted', 'owner', '2', 'jinwoo', 'Deleted owner: jinwoo (solo)', '::1', '2026-05-15 14:17:28');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('11', '1', 'superAdmin', 'superadmin_logout', 'superadmin', '1', 'superAdmin', 'Superadmin logged out', '::1', '2026-05-15 14:18:59');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('12', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-15 14:29:54');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('13', '1', 'superAdmin', 'superadmin_logout', 'superadmin', '1', 'superAdmin', 'Superadmin logged out', '::1', '2026-05-15 14:59:11');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('14', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-16 11:45:52');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('15', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-16 18:31:07');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('16', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-17 14:04:14');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('17', '1', 'superAdmin', 'superadmin_logout', 'superadmin', '1', 'superAdmin', 'Superadmin logged out', '::1', '2026-05-17 14:28:07');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('18', NULL, 'superadmin', 'owner_created', 'owner', NULL, 'ninagraceteroyang@gmail.com', 'New owner registered: ninagraceteroyang@gmail.com (cafees)', '::1', '2026-05-17 14:29:25');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('19', '1', 'superAdmin', 'superadmin_login', 'superadmin', '1', 'superAdmin', 'Superadmin logged in successfully', '::1', '2026-05-17 14:35:51');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('20', '1', 'superAdmin', 'backup_created', 'backup', NULL, 'backup_manual_20260517_143612.sql', 'Backup label: manual, tables: 10', '::1', '2026-05-17 14:36:12');

DROP TABLE IF EXISTS `carts`;
CREATE TABLE `carts` (
  `cart_id` int NOT NULL AUTO_INCREMENT,
  `customer_id` int NOT NULL,
  `menu_item_id` int NOT NULL,
  `quantity` int NOT NULL DEFAULT '1',
  `subtotal` decimal(10,2) NOT NULL DEFAULT '0.00',
  `date_added` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cart_id`),
  KEY `customer_id` (`customer_id`),
  KEY `menu_item_id` (`menu_item_id`),
  CONSTRAINT `carts_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`customer_id`) ON DELETE CASCADE,
  CONSTRAINT `carts_ibfk_2` FOREIGN KEY (`menu_item_id`) REFERENCES `menu_items` (`menu_item_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `customers`;
CREATE TABLE `customers` (
  `customer_id` int NOT NULL AUTO_INCREMENT,
  `order_number` varchar(20) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `table_number` varchar(20) DEFAULT NULL,
  `session_start` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `session_end` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `menu_items`;
CREATE TABLE `menu_items` (
  `menu_item_id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int NOT NULL,
  `item_name` varchar(120) NOT NULL,
  `description` text,
  `price` decimal(10,2) NOT NULL,
  `stock_quantity` int NOT NULL DEFAULT '0',
  `category` varchar(60) NOT NULL DEFAULT 'Uncategorized',
  `is_available` tinyint(1) NOT NULL DEFAULT '1',
  `image_url` varchar(500) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`menu_item_id`),
  KEY `admin_id` (`admin_id`),
  CONSTRAINT `menu_items_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('1', '4', 'ice coffee', 'coffee', '49.00', '100', 'coffee', '1', NULL, '2026-05-17 14:31:42', '2026-05-17 14:31:42');
INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('2', '4', 'hot choco', 'choco lattee', '49.00', '100', 'hot lattee', '1', NULL, '2026-05-17 14:32:41', '2026-05-17 14:32:41');

DROP TABLE IF EXISTS `order_items`;
CREATE TABLE `order_items` (
  `order_item_id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `menu_item_id` int DEFAULT NULL,
  `item_name` varchar(120) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `quantity` int NOT NULL,
  `subtotal` decimal(10,2) NOT NULL,
  PRIMARY KEY (`order_item_id`),
  KEY `order_id` (`order_id`),
  KEY `menu_item_id` (`menu_item_id`),
  CONSTRAINT `order_items_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`order_id`) ON DELETE CASCADE,
  CONSTRAINT `order_items_ibfk_2` FOREIGN KEY (`menu_item_id`) REFERENCES `menu_items` (`menu_item_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders` (
  `order_id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int NOT NULL,
  `customer_id` int NOT NULL,
  `order_status` enum('Queued','Preparing','Served','Completed','Cancelled') NOT NULL DEFAULT 'Queued',
  `total_amount` decimal(10,2) NOT NULL DEFAULT '0.00',
  `queue_number` int NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`order_id`),
  KEY `admin_id` (`admin_id`),
  KEY `customer_id` (`customer_id`),
  CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE CASCADE,
  CONSTRAINT `orders_ibfk_2` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`customer_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `payments`;
CREATE TABLE `payments` (
  `payment_id` int NOT NULL AUTO_INCREMENT,
  `order_id` int NOT NULL,
  `payment_method` enum('Cash','GCash','Credit Card') NOT NULL DEFAULT 'Cash',
  `amount_paid` decimal(10,2) NOT NULL,
  `change_given` decimal(10,2) NOT NULL DEFAULT '0.00',
  `receipt_number` varchar(30) NOT NULL,
  `payment_status` enum('Completed','Pending','Failed') NOT NULL DEFAULT 'Pending',
  `payment_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`payment_id`),
  UNIQUE KEY `order_id` (`order_id`),
  UNIQUE KEY `receipt_number` (`receipt_number`),
  CONSTRAINT `payments_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `orders` (`order_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `staffs`;
CREATE TABLE `staffs` (
  `staff_id` int NOT NULL AUTO_INCREMENT,
  `admin_id` int NOT NULL,
  `fullname` varchar(100) NOT NULL,
  `role` enum('Cashier','Kitchen') NOT NULL DEFAULT 'Cashier',
  `pin` varchar(255) DEFAULT NULL,
  `status` enum('Active','Inactive') NOT NULL DEFAULT 'Active',
  `shift_start` time DEFAULT NULL,
  `shift_end` time DEFAULT NULL,
  `login_fail_count` int NOT NULL DEFAULT '0',
  `last_fail_at` timestamp NULL DEFAULT NULL,
  `last_login_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`staff_id`),
  KEY `admin_id` (`admin_id`),
  CONSTRAINT `staffs_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`admin_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`) VALUES ('2', '3', 'hinata', 'Cashier', '$2y$12$yO4a3pZOFpPfNcOW8thDI.8/wIYh5502PiBVptOtjOLG16SgkG0y.', 'Active', '13:15:00', '17:15:00', '0', NULL, '2026-05-15 14:15:56', '2026-05-15 14:14:35');

SET FOREIGN_KEY_CHECKS=1;
