<?php
// ── Output buffer: catches any stray PHP warnings/notices before headers ──────
ob_start();

ini_set('display_errors', 0);
error_reporting(0);

// Ensure JSON is ALWAYS what goes back, even on fatal errors
register_shutdown_function(function () {
    $err = error_get_last();
    if ($err && in_array($err['type'], [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR])) {
        ob_end_clean();
        if (!headers_sent()) header('Content-Type: application/json');
        echo json_encode(['success' => false, 'message' => 'PHP fatal error: ' . $err['message']]);
    }
});

set_exception_handler(function ($e) {
    ob_end_clean();
    if (!headers_sent()) header('Content-Type: application/json');
    echo json_encode(['success' => false, 'message' => $e->getMessage()]);
    exit;
});

// ── Session ───────────────────────────────────────────────────────────────────
session_start();

ob_end_clean();
header('Content-Type: application/json');

// ── Auth guard — admin (owner) only ──────────────────────────────────────────
if (!isset($_SESSION['admin_id'])) {
    http_response_code(403);
    echo json_encode(['success' => false, 'message' => 'Unauthorized. Please log in as admin.']);
    exit;
}

$admin_id = (int)$_SESSION['admin_id'];

// ── Bootstrap ─────────────────────────────────────────────────────────────────
$root = dirname(__DIR__);   // project root (parent of dashboard/)

require_once $root . '/config/database.php';
require_once $root . '/config/audit_helper.php';

$db   = new Database();
$conn = $db->connect();

$action = $_GET['action'] ?? $_POST['action'] ?? '';

// ── Backup directory — per-admin subfolder ────────────────────────────────────
$backupDir = $root . '/backups/admin_' . $admin_id;
if (!is_dir($backupDir)) {
    if (!mkdir($backupDir, 0755, true)) {
        echo json_encode(['success' => false, 'message' => 'Cannot create backups directory. Check folder permissions.']);
        exit;
    }
}

// ════════════════════════════════════════════════════════════
//  CREATE BACKUP — exports only this admin's data as SQL
// ════════════════════════════════════════════════════════════
if ($action === 'create') {
    try {
        $label     = preg_replace('/[^a-zA-Z0-9_\-]/', '_', trim($_POST['label'] ?? ''));
        $label     = $label !== '' ? $label : 'manual';
        $timestamp = date('Ymd_His');
        $filename  = "backup_{$label}_{$timestamp}.sql";
        $filepath  = $backupDir . '/' . $filename;

        $fastfood  = htmlspecialchars($_SESSION['fastfood_name'] ?? 'admin');
        $username  = $_SESSION['username'] ?? 'admin';

        $sql  = "-- iPOS Admin Backup | Admin ID: {$admin_id} | Label: {$label}\n";
        $sql .= "-- Restaurant: {$fastfood} | Created: " . date('Y-m-d H:i:s') . "\n";
        $sql .= "-- Generated by iPOS Admin Backup & Recovery\n\n";
        $sql .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

        // ── menu_items ────────────────────────────────────────────────────────
        $createRes = $conn->query("SHOW CREATE TABLE `menu_items`");
        $createRow = $createRes->fetch(PDO::FETCH_NUM);
        $sql .= "-- TABLE: menu_items (admin_id = {$admin_id})\n";
        $sql .= "DELETE FROM `menu_items` WHERE `admin_id` = {$admin_id};\n\n";

        $rows = $conn->prepare("SELECT * FROM `menu_items` WHERE admin_id = ?");
        $rows->execute([$admin_id]);
        $cols = [];
        for ($i = 0; $i < $rows->columnCount(); $i++) {
            $meta   = $rows->getColumnMeta($i);
            $cols[] = "`{$meta['name']}`";
        }
        $colList = implode(', ', $cols);
        $menuCount = 0;
        while ($row = $rows->fetch(PDO::FETCH_NUM)) {
            $vals = array_map(fn($v) => $v === null ? 'NULL' : $conn->quote($v), $row);
            $sql .= "INSERT INTO `menu_items` ({$colList}) VALUES (" . implode(', ', $vals) . ");\n";
            $menuCount++;
        }
        $sql .= "\n";

        // ── staffs ────────────────────────────────────────────────────────────
        $sql .= "-- TABLE: staffs (admin_id = {$admin_id})\n";
        $sql .= "DELETE FROM `staffs` WHERE `admin_id` = {$admin_id};\n\n";

        $rows = $conn->prepare("SELECT * FROM `staffs` WHERE admin_id = ?");
        $rows->execute([$admin_id]);
        $cols = [];
        for ($i = 0; $i < $rows->columnCount(); $i++) {
            $meta   = $rows->getColumnMeta($i);
            $cols[] = "`{$meta['name']}`";
        }
        $colList = implode(', ', $cols);
        $staffCount = 0;
        while ($row = $rows->fetch(PDO::FETCH_NUM)) {
            $vals = array_map(fn($v) => $v === null ? 'NULL' : $conn->quote($v), $row);
            $sql .= "INSERT INTO `staffs` ({$colList}) VALUES (" . implode(', ', $vals) . ");\n";
            $staffCount++;
        }
        $sql .= "\n";

        // ── orders + order_items ──────────────────────────────────────────────
        $sql .= "-- TABLE: orders (admin_id = {$admin_id})\n";
        $sql .= "DELETE FROM `orders` WHERE `admin_id` = {$admin_id};\n\n";

        $orderRows = $conn->prepare("SELECT * FROM `orders` WHERE admin_id = ?");
        $orderRows->execute([$admin_id]);
        $cols = [];
        for ($i = 0; $i < $orderRows->columnCount(); $i++) {
            $meta   = $orderRows->getColumnMeta($i);
            $cols[] = "`{$meta['name']}`";
        }
        $colList    = implode(', ', $cols);
        $orderIds   = [];
        $orderCount = 0;
        while ($row = $orderRows->fetch(PDO::FETCH_NUM)) {
            $vals = array_map(fn($v) => $v === null ? 'NULL' : $conn->quote($v), $row);
            $sql .= "INSERT INTO `orders` ({$colList}) VALUES (" . implode(', ', $vals) . ");\n";
            $orderIds[] = (int)$row[0]; // order_id is first column
            $orderCount++;
        }
        $sql .= "\n";

        // order_items tied to this admin's orders
        if (!empty($orderIds)) {
            $placeholders = implode(',', array_fill(0, count($orderIds), '?'));
            $sql .= "-- TABLE: order_items for admin_id = {$admin_id}\n";

            $oiRows = $conn->prepare("SELECT * FROM `order_items` WHERE order_id IN ({$placeholders})");
            $oiRows->execute($orderIds);
            $cols = [];
            for ($i = 0; $i < $oiRows->columnCount(); $i++) {
                $meta   = $oiRows->getColumnMeta($i);
                $cols[] = "`{$meta['name']}`";
            }
            $colList = implode(', ', $cols);
            while ($row = $oiRows->fetch(PDO::FETCH_NUM)) {
                $vals = array_map(fn($v) => $v === null ? 'NULL' : $conn->quote($v), $row);
                $sql .= "INSERT INTO `order_items` ({$colList}) VALUES (" . implode(', ', $vals) . ");\n";
            }
            $sql .= "\n";

            // payments tied to this admin's orders
            $sql .= "-- TABLE: payments for admin_id = {$admin_id}\n";
            $payRows = $conn->prepare("SELECT * FROM `payments` WHERE order_id IN ({$placeholders})");
            $payRows->execute($orderIds);
            $cols = [];
            for ($i = 0; $i < $payRows->columnCount(); $i++) {
                $meta   = $payRows->getColumnMeta($i);
                $cols[] = "`{$meta['name']}`";
            }
            $colList = implode(', ', $cols);
            while ($row = $payRows->fetch(PDO::FETCH_NUM)) {
                $vals = array_map(fn($v) => $v === null ? 'NULL' : $conn->quote($v), $row);
                $sql .= "INSERT INTO `payments` ({$colList}) VALUES (" . implode(', ', $vals) . ");\n";
            }
            $sql .= "\n";
        }

        // ── audit_log entries for this admin ─────────────────────────────────
        $sql .= "-- TABLE: audit_log (admin_id = {$admin_id})\n";
        $auditRows = $conn->prepare("SELECT * FROM `audit_log` WHERE admin_id = ? ORDER BY log_id ASC");
        $auditRows->execute([$admin_id]);
        $cols = [];
        for ($i = 0; $i < $auditRows->columnCount(); $i++) {
            $meta   = $auditRows->getColumnMeta($i);
            $cols[] = "`{$meta['name']}`";
        }
        $colList = implode(', ', $cols);
        while ($row = $auditRows->fetch(PDO::FETCH_NUM)) {
            $vals = array_map(fn($v) => $v === null ? 'NULL' : $conn->quote($v), $row);
            $sql .= "INSERT INTO `audit_log` ({$colList}) VALUES (" . implode(', ', $vals) . ");\n";
        }
        $sql .= "\n";

        $sql .= "SET FOREIGN_KEY_CHECKS=1;\n";

        if (file_put_contents($filepath, $sql) === false) {
            echo json_encode(['success' => false, 'message' => 'Cannot write backup file. Check permissions on the backups/ folder.']);
            exit;
        }

        // Update index
        $indexFile = $backupDir . '/index.json';
        $index     = file_exists($indexFile) ? (json_decode(file_get_contents($indexFile), true) ?? []) : [];
        $index[]   = [
            'filename'   => $filename,
            'label'      => $label,
            'created_at' => date('Y-m-d H:i:s'),
            'size'       => filesize($filepath),
            'menu_items' => $menuCount,
            'staffs'     => $staffCount,
            'orders'     => $orderCount,
            'created_by' => $username,
        ];
        file_put_contents($indexFile, json_encode($index, JSON_PRETTY_PRINT));

        audit_log($conn, $_SESSION, 'admin_backup_created', 'backup', null, $filename,
            "Admin backup created: {$filename} | menu:{$menuCount}, staff:{$staffCount}, orders:{$orderCount}");

        echo json_encode([
            'success'  => true,
            'filename' => $filename,
            'message'  => "Backup \"{$label}\" created successfully ({$filename}).",
        ]);
    } catch (Exception $e) {
        echo json_encode(['success' => false, 'message' => 'Backup failed: ' . $e->getMessage()]);
    }
    exit;
}

// ════════════════════════════════════════════════════════════
//  LIST BACKUPS
// ════════════════════════════════════════════════════════════
if ($action === 'list') {
    $indexFile = $backupDir . '/index.json';
    $index     = [];

    if (file_exists($indexFile)) {
        $index = json_decode(file_get_contents($indexFile), true) ?? [];
        $index = array_values(array_filter($index, fn($b) => file_exists($backupDir . '/' . $b['filename'])));
        usort($index, fn($a, $b) => strcmp($b['created_at'], $a['created_at']));
        foreach ($index as &$entry) {
            $entry['size'] = filesize($backupDir . '/' . $entry['filename']);
        }
        unset($entry);
    }

    echo json_encode(['success' => true, 'backups' => $index]);
    exit;
}

// ════════════════════════════════════════════════════════════
//  DOWNLOAD BACKUP
// ════════════════════════════════════════════════════════════
if ($action === 'download') {
    $filename = basename($_GET['file'] ?? '');
    $filepath = $backupDir . '/' . $filename;

    if ($filename === '' || pathinfo($filename, PATHINFO_EXTENSION) !== 'sql' || !file_exists($filepath)) {
        http_response_code(404);
        header('Content-Type: text/plain');
        echo 'Backup file not found.';
        exit;
    }

    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Content-Length: ' . filesize($filepath));
    header('Cache-Control: no-cache');
    readfile($filepath);
    exit;
}

// ════════════════════════════════════════════════════════════
//  DELETE BACKUP
// ════════════════════════════════════════════════════════════
if ($action === 'delete') {
    $filename = basename($_POST['file'] ?? '');
    $filepath = $backupDir . '/' . $filename;

    if ($filename === '' || pathinfo($filename, PATHINFO_EXTENSION) !== 'sql' || !file_exists($filepath)) {
        echo json_encode(['success' => false, 'message' => 'File not found or already deleted.']);
        exit;
    }

    unlink($filepath);

    $indexFile = $backupDir . '/index.json';
    if (file_exists($indexFile)) {
        $index = json_decode(file_get_contents($indexFile), true) ?? [];
        $index = array_values(array_filter($index, fn($b) => $b['filename'] !== $filename));
        file_put_contents($indexFile, json_encode($index, JSON_PRETTY_PRINT));
    }

    audit_log($conn, $_SESSION, 'admin_backup_deleted', 'backup', null, $filename, "Admin backup deleted: {$filename}");
    echo json_encode(['success' => true, 'message' => "Backup \"{$filename}\" deleted."]);
    exit;
}

// ════════════════════════════════════════════════════════════
//  RESTORE BACKUP
// ════════════════════════════════════════════════════════════
if ($action === 'restore') {
    try {
        $sql = '';

        if (!empty($_POST['file'])) {
            $filename = basename($_POST['file']);
            $filepath = $backupDir . '/' . $filename;
            if (!file_exists($filepath) || pathinfo($filename, PATHINFO_EXTENSION) !== 'sql') {
                echo json_encode(['success' => false, 'message' => 'Backup file not found on server.']);
                exit;
            }
            $sql = file_get_contents($filepath);

        } elseif (isset($_FILES['backup_file']) && $_FILES['backup_file']['error'] === UPLOAD_ERR_OK) {
            $ext = strtolower(pathinfo($_FILES['backup_file']['name'], PATHINFO_EXTENSION));
            if ($ext !== 'sql') {
                echo json_encode(['success' => false, 'message' => 'Only .sql files are accepted.']);
                exit;
            }
            $sql = file_get_contents($_FILES['backup_file']['tmp_name']);
        } else {
            $uploadErr = $_FILES['backup_file']['error'] ?? 'none';
            echo json_encode(['success' => false, 'message' => "No backup source provided (upload error: {$uploadErr})."]);
            exit;
        }

        if (empty(trim($sql))) {
            echo json_encode(['success' => false, 'message' => 'Backup file is empty.']);
            exit;
        }

        // Strip comment lines, split on ";\n" boundaries
        $sql        = preg_replace('/^--[^\n]*\n?/m', '', $sql);
        $statements = array_filter(array_map('trim', explode(";\n", $sql)), fn($s) => $s !== '');

        $conn->exec("SET FOREIGN_KEY_CHECKS=0");
        foreach ($statements as $stmt) {
            $stmt = trim($stmt);
            if ($stmt === '') continue;
            // Use INSERT IGNORE for audit_log to skip duplicate primary key conflicts
            if (stripos($stmt, 'INSERT INTO `audit_log`') === 0) {
                $stmt = preg_replace('/^INSERT\s+INTO/i', 'INSERT IGNORE INTO', $stmt);
            }
            $conn->exec($stmt);
        }
        $conn->exec("SET FOREIGN_KEY_CHECKS=1");

        $restore_source = !empty($_POST['file'])
            ? $_POST['file']
            : ($_FILES['backup_file']['name'] ?? 'uploaded file');

        $source_type = !empty($_POST['file']) ? 'server' : 'upload';
        $restored_at = date('Y-m-d H:i:s');

        // Insert into admin_restore_logs
        try {
            $logStmt = $conn->prepare(
                "INSERT INTO admin_restore_logs (admin_id, filename, restored_by, restored_at, source)
                 VALUES (:admin_id, :filename, :restored_by, :restored_at, :source)"
            );
            $logStmt->execute([
                ':admin_id'    => $admin_id,
                ':filename'    => $restore_source,
                ':restored_by' => $_SESSION['username'] ?? 'admin',
                ':restored_at' => $restored_at,
                ':source'      => $source_type,
            ]);
        } catch (Exception $logEx) {
            // Non-fatal: don't block the restore response
            error_log('admin_restore_logs insert failed: ' . $logEx->getMessage());
        }

        audit_log($conn, $_SESSION, 'admin_backup_restored', 'backup', null, $restore_source,
    "Admin database restored from: {$restore_source}");

echo json_encode([
    'success'        => true,
    'message'        => 'Data restored successfully. Please verify your records.',
    'restore_source' => $restore_source,
    'restored_at'    => $restored_at,
]);
    } catch (Exception $e) {
        echo json_encode(['success' => false, 'message' => 'Restore failed: ' . $e->getMessage()]);
    }
    exit;
}

// ════════════════════════════════════════════════════════════
//  RENAME BACKUP LABEL
// ════════════════════════════════════════════════════════════
if ($action === 'rename') {
    $filename = basename($_POST['file']  ?? '');
    $newLabel = trim($_POST['label']     ?? '');

    if ($filename === '' || pathinfo($filename, PATHINFO_EXTENSION) !== 'sql') {
        echo json_encode(['success' => false, 'message' => 'Invalid filename.']);
        exit;
    }
    if ($newLabel === '') {
        echo json_encode(['success' => false, 'message' => 'Label cannot be empty.']);
        exit;
    }

    $newLabel  = trim(preg_replace('/[^a-zA-Z0-9_\- ]/', '', $newLabel));
    $indexFile = $backupDir . '/index.json';

    if (!file_exists($indexFile)) {
        echo json_encode(['success' => false, 'message' => 'Backup index not found.']);
        exit;
    }

    $index   = json_decode(file_get_contents($indexFile), true) ?? [];
    $updated = false;
    foreach ($index as &$entry) {
        if ($entry['filename'] === $filename) {
            $entry['label'] = $newLabel;
            $updated = true;
            break;
        }
    }
    unset($entry);

    if (!$updated) {
        echo json_encode(['success' => false, 'message' => 'Backup not found in index.']);
        exit;
    }

    file_put_contents($indexFile, json_encode($index, JSON_PRETTY_PRINT));
    echo json_encode(['success' => true, 'message' => 'Label updated.', 'label' => $newLabel]);
    exit;
}

// ════════════════════════════════════════════════════════════
//  RESTORE LOGS
// ════════════════════════════════════════════════════════════
if ($action === 'restore_logs') {
    try {
        $stmt = $conn->prepare(
            "SELECT restore_id, filename, restored_by, restored_at, source
             FROM admin_restore_logs
             WHERE admin_id = :admin_id
             ORDER BY restored_at DESC
             LIMIT 50"
        );
        $stmt->execute([':admin_id' => $admin_id]);
        $logs = $stmt->fetchAll(PDO::FETCH_ASSOC);
        echo json_encode(['success' => true, 'logs' => $logs, 'total' => count($logs)]);
    } catch (Exception $e) {
        echo json_encode(['success' => false, 'logs' => [], 'total' => 0]);
    }
    exit;
}

// ── Unknown action ────────────────────────────────────────────────────────────
http_response_code(400);
echo json_encode(['success' => false, 'message' => "Unknown action: \"{$action}\"."]);