<?php
// ── Output buffer: catches any stray PHP warnings/notices before headers ──────
ob_start();

ini_set('display_errors', 0);
error_reporting(0);

// Ensure JSON is ALWAYS what goes back, even on fatal errors
register_shutdown_function(function () {
    $err = error_get_last();
    if ($err && in_array($err['type'], [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR])) {
        ob_end_clean();
        if (!headers_sent()) header('Content-Type: application/json');
        echo json_encode(['success' => false, 'message' => 'PHP fatal error: ' . $err['message']]);
    }
});

set_exception_handler(function ($e) {
    ob_end_clean();
    if (!headers_sent()) header('Content-Type: application/json');
    echo json_encode(['success' => false, 'message' => $e->getMessage()]);
    exit;
});

// ── Session (must start before any output) ────────────────────────────────────
session_start();

// ── Now it is safe to send headers ───────────────────────────────────────────
ob_end_clean();   // discard anything that leaked before this point
header('Content-Type: application/json');

// ── Locate project root (backup_handler.php lives at project root) ────────────
$root = dirname(__DIR__);   // e.g. /var/www/html/ipos

$dbConfig = $root . '/config/database.php';
if (!file_exists($dbConfig)) {
    echo json_encode([
        'success' => false,
        'message' => 'Cannot find config/database.php. '
                   . 'backup_handler.php must sit at the project root (same folder as login.php).',
    ]);
    exit;
}
require_once $dbConfig;
require_once $root . '/config/audit_helper.php';

// ── Auth guard ────────────────────────────────────────────────────────────────
if (!isset($_SESSION['role']) || $_SESSION['role'] !== 'superadmin') {
    http_response_code(403);
    echo json_encode(['success' => false, 'message' => 'Unauthorized. Please log in as superadmin.']);
    exit;
}

$db   = new Database();
$conn = $db->connect();

$action = $_GET['action'] ?? $_POST['action'] ?? '';

// ── Backup directory ──────────────────────────────────────────────────────────
$backupDir = $root . '/backups';
if (!is_dir($backupDir)) {
    if (!mkdir($backupDir, 0755, true)) {
        echo json_encode(['success' => false, 'message' => 'Cannot create backups/ directory. Check folder permissions.']);
        exit;
    }
}

// ── Helper: parse DB credentials from database.php ───────────────────────────
function getDbCredentials(string $root): array
{
    $src = file_get_contents($root . '/config/database.php');
    preg_match('/\$host\s*=\s*["\']([^"\']+)["\']/',     $src, $h);
    preg_match('/\$dbname\s*=\s*["\']([^"\']+)["\']/',   $src, $d);
    preg_match('/\$username\s*=\s*["\']([^"\']+)["\']/', $src, $u);
    preg_match('/\$password\s*=\s*["\']([^"\']*)["\']/', $src, $p);
    return [
        'host'     => $h[1] ?? 'localhost',
        'dbname'   => $d[1] ?? 'ipos_db',
        'username' => $u[1] ?? 'root',
        'password' => $p[1] ?? '',
    ];
}

// ════════════════════════════════════════════════════════════
//  CREATE BACKUP
// ════════════════════════════════════════════════════════════
if ($action === 'create') {
    try {
        $label     = preg_replace('/[^a-zA-Z0-9_\-]/', '_', trim($_POST['label'] ?? ''));
        $label     = $label !== '' ? $label : 'manual';
        $timestamp = date('Ymd_His');
        $filename  = "backup_{$label}_{$timestamp}.sql";
        $filepath  = $backupDir . '/' . $filename;

        // List all tables
        $tables = [];
        $res    = $conn->query("SHOW TABLES");
        while ($row = $res->fetch(PDO::FETCH_NUM)) {
            $tables[] = $row[0];
        }

        if (empty($tables)) {
            echo json_encode(['success' => false, 'message' => 'No tables found in the database.']);
            exit;
        }

        $sql  = "-- iPOS Backup | Label: {$label} | Created: " . date('Y-m-d H:i:s') . "\n";
        $sql .= "-- Generated by iPOS Superadmin Backup & Recovery\n\n";
        $sql .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

        foreach ($tables as $table) {
            $createRes = $conn->query("SHOW CREATE TABLE `{$table}`");
            $createRow = $createRes->fetch(PDO::FETCH_NUM);
            $sql .= "DROP TABLE IF EXISTS `{$table}`;\n";
            $sql .= $createRow[1] . ";\n\n";

            $rows    = $conn->query("SELECT * FROM `{$table}`");
            $cols    = [];
            for ($i = 0; $i < $rows->columnCount(); $i++) {
                $meta   = $rows->getColumnMeta($i);
                $cols[] = "`{$meta['name']}`";
            }
            $colList = implode(', ', $cols);

            while ($row = $rows->fetch(PDO::FETCH_NUM)) {
                $vals = array_map(fn($v) => $v === null ? 'NULL' : $conn->quote($v), $row);
                $sql .= "INSERT INTO `{$table}` ({$colList}) VALUES (" . implode(', ', $vals) . ");\n";
            }
            $sql .= "\n";
        }
        $sql .= "SET FOREIGN_KEY_CHECKS=1;\n";

        if (file_put_contents($filepath, $sql) === false) {
            echo json_encode(['success' => false, 'message' => 'Cannot write backup file. Check permissions on the backups/ folder.']);
            exit;
        }

        // Update index
        $indexFile = $backupDir . '/index.json';
        $index     = file_exists($indexFile) ? (json_decode(file_get_contents($indexFile), true) ?? []) : [];
        $index[]   = [
            'filename'   => $filename,
            'label'      => $label,
            'created_at' => date('Y-m-d H:i:s'),
            'size'       => filesize($filepath),
            'tables'     => count($tables),
            'created_by' => $_SESSION['username'] ?? 'superadmin',
        ];
        file_put_contents($indexFile, json_encode($index, JSON_PRETTY_PRINT));

        echo json_encode(['success' => true, 'filename' => $filename, 'message' => "Backup \"{$label}\" created successfully ({$filename})."]
        );
        audit_log($conn, $_SESSION, 'backup_created', 'backup', null, $filename, "Backup label: {$label}, tables: " . count($tables));
    } catch (Exception $e) {
        echo json_encode(['success' => false, 'message' => 'Backup failed: ' . $e->getMessage()]);
    }
    exit;
}

// ════════════════════════════════════════════════════════════
//  LIST BACKUPS
// ════════════════════════════════════════════════════════════
if ($action === 'list') {
    $indexFile = $backupDir . '/index.json';
    $index     = [];

    if (file_exists($indexFile)) {
        $index = json_decode(file_get_contents($indexFile), true) ?? [];
        // Remove entries whose files have been deleted externally
        $index = array_values(array_filter($index, fn($b) => file_exists($backupDir . '/' . $b['filename'])));
        // Sort newest first
        usort($index, fn($a, $b) => strcmp($b['created_at'], $a['created_at']));
        // Refresh live file size
        foreach ($index as &$entry) {
            $entry['size'] = filesize($backupDir . '/' . $entry['filename']);
        }
        unset($entry);
    }

    echo json_encode(['success' => true, 'backups' => $index]);
    exit;
}

// ════════════════════════════════════════════════════════════
//  DOWNLOAD BACKUP
// ════════════════════════════════════════════════════════════
if ($action === 'download') {
    $filename = basename($_GET['file'] ?? '');
    $filepath = $backupDir . '/' . $filename;

    if ($filename === '' || pathinfo($filename, PATHINFO_EXTENSION) !== 'sql' || !file_exists($filepath)) {
        http_response_code(404);
        // Override content-type for plain error text
        header('Content-Type: text/plain');
        echo 'Backup file not found.';
        exit;
    }

    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Content-Length: ' . filesize($filepath));
    header('Cache-Control: no-cache');
    readfile($filepath);
    exit;
}

// ════════════════════════════════════════════════════════════
//  DELETE BACKUP
// ════════════════════════════════════════════════════════════
if ($action === 'delete') {
    $filename = basename($_POST['file'] ?? '');
    $filepath = $backupDir . '/' . $filename;

    if ($filename === '' || pathinfo($filename, PATHINFO_EXTENSION) !== 'sql' || !file_exists($filepath)) {
        echo json_encode(['success' => false, 'message' => 'File not found or already deleted.']);
        exit;
    }

    unlink($filepath);

    $indexFile = $backupDir . '/index.json';
    if (file_exists($indexFile)) {
        $index = json_decode(file_get_contents($indexFile), true) ?? [];
        $index = array_values(array_filter($index, fn($b) => $b['filename'] !== $filename));
        file_put_contents($indexFile, json_encode($index, JSON_PRETTY_PRINT));
    }

    audit_log($conn, $_SESSION, 'backup_deleted', 'backup', null, $filename, "Backup file deleted: {$filename}");
    echo json_encode(['success' => true, 'message' => "Backup \"{$filename}\" deleted."]);
    exit;
}

// ════════════════════════════════════════════════════════════
//  RESTORE BACKUP
// ════════════════════════════════════════════════════════════
if ($action === 'restore') {
    try {
        $sql = '';

        if (!empty($_POST['file'])) {
            // Restore from a saved backup on the server
            $filename = basename($_POST['file']);
            $filepath = $backupDir . '/' . $filename;
            if (!file_exists($filepath) || pathinfo($filename, PATHINFO_EXTENSION) !== 'sql') {
                echo json_encode(['success' => false, 'message' => 'Backup file not found on server.']);
                exit;
            }
            $sql = file_get_contents($filepath);

        } elseif (isset($_FILES['backup_file']) && $_FILES['backup_file']['error'] === UPLOAD_ERR_OK) {
            // Restore from an uploaded file
            $ext = strtolower(pathinfo($_FILES['backup_file']['name'], PATHINFO_EXTENSION));
            if ($ext !== 'sql') {
                echo json_encode(['success' => false, 'message' => 'Only .sql files are accepted.']);
                exit;
            }
            $sql = file_get_contents($_FILES['backup_file']['tmp_name']);

        } else {
            $uploadErr = $_FILES['backup_file']['error'] ?? 'none';
            echo json_encode(['success' => false, 'message' => "No backup source provided (upload error: {$uploadErr})."]);
            exit;
        }

        if (empty(trim($sql))) {
            echo json_encode(['success' => false, 'message' => 'Backup file is empty.']);
            exit;
        }

        // Strip comment lines, then split on ";\n" boundaries
        $sql        = preg_replace('/^--[^\n]*\n?/m', '', $sql);
        $statements = array_filter(array_map('trim', explode(";\n", $sql)), fn($s) => $s !== '');

        $conn->exec("SET FOREIGN_KEY_CHECKS=0");
        foreach ($statements as $stmt) {
            if (trim($stmt) !== '') {
                $conn->exec($stmt);
            }
        }
        $conn->exec("SET FOREIGN_KEY_CHECKS=1");

        $restore_source = !empty($_POST['file']) ? $_POST['file'] : ($_FILES['backup_file']['name'] ?? 'uploaded file');
        audit_log($conn, $_SESSION, 'backup_restored', 'backup', null, $restore_source, "Database restored from: {$restore_source}");
        echo json_encode(['success' => true, 'message' => 'Database restored successfully. Please verify your data.']);
    } catch (Exception $e) {
        echo json_encode(['success' => false, 'message' => 'Restore failed: ' . $e->getMessage()]);
    }
    exit;
}

// ════════════════════════════════════════════════════════════
//  RENAME BACKUP LABEL
// ════════════════════════════════════════════════════════════
if ($action === 'rename') {
    $filename = basename($_POST['file']  ?? '');
    $newLabel = trim($_POST['label']     ?? '');

    if ($filename === '' || pathinfo($filename, PATHINFO_EXTENSION) !== 'sql') {
        echo json_encode(['success' => false, 'message' => 'Invalid filename.']);
        exit;
    }
    if ($newLabel === '') {
        echo json_encode(['success' => false, 'message' => 'Label cannot be empty.']);
        exit;
    }

    // Sanitise label (same rules as create)
    $newLabel = preg_replace('/[^a-zA-Z0-9_\- ]/', '', $newLabel);
    $newLabel = trim($newLabel);

    $indexFile = $backupDir . '/index.json';
    if (!file_exists($indexFile)) {
        echo json_encode(['success' => false, 'message' => 'Backup index not found.']);
        exit;
    }

    $index   = json_decode(file_get_contents($indexFile), true) ?? [];
    $updated = false;
    foreach ($index as &$entry) {
        if ($entry['filename'] === $filename) {
            $entry['label'] = $newLabel;
            $updated = true;
            break;
        }
    }
    unset($entry);

    if (!$updated) {
        echo json_encode(['success' => false, 'message' => 'Backup not found in index.']);
        exit;
    }

    file_put_contents($indexFile, json_encode($index, JSON_PRETTY_PRINT));
    echo json_encode(['success' => true, 'message' => 'Label updated successfully.', 'label' => $newLabel]);
    exit;
}

// ── Unknown action ────────────────────────────────────────────────────────────
http_response_code(400);
echo json_encode(['success' => false, 'message' => "Unknown action: \"{$action}\"."]);