-- iPOS Admin Backup | Admin ID: 5 | Label: manual
-- Restaurant: Fstfd | Created: 2026-05-18 16:52:40
-- Generated by iPOS Admin Backup & Recovery

SET FOREIGN_KEY_CHECKS=0;

-- TABLE: menu_items (admin_id = 5)
DELETE FROM `menu_items` WHERE `admin_id` = 5;

INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('3', '5', 'isaw', '', '7.00', '100', 'isaw', '1', NULL, '2026-05-17 18:02:54', '2026-05-17 18:02:54');
INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('4', '5', 'hotdog', '', '20.00', '150', 'hotdog', '1', NULL, '2026-05-17 18:03:26', '2026-05-17 18:03:26');
INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('5', '5', 'quick2', '', '10.00', '96', 'quick2', '1', NULL, '2026-05-17 18:04:07', '2026-05-17 18:13:47');

-- TABLE: staffs (admin_id = 5)
DELETE FROM `staffs` WHERE `admin_id` = 5;

INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`) VALUES ('3', '5', 'hapi', 'Cashier', '$2y$12$THbOPJRCL2EXeEdcozQxquDpgZ.7Zq1gzLJ3GXl9F.TxcuauflK/a', 'Active', '06:01:00', '18:00:00', '0', NULL, '2026-05-18 02:33:03', '2026-05-17 18:05:08');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`) VALUES ('4', '5', 'lucy', 'Kitchen', '$2y$12$P9jTgmGHpW7ukFza64QyF.FuA02Q2mGP7HFOKx1PA50aDF/mNDFd.', 'Active', '06:00:00', '18:00:00', '0', NULL, '2026-05-17 18:17:42', '2026-05-17 18:12:13');

-- TABLE: orders (admin_id = 5)
DELETE FROM `orders` WHERE `admin_id` = 5;

INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`, `updated_at`) VALUES ('1', '5', '1', 'Served', '10.00', '1', '2026-05-17 18:12:46', '2026-05-17 18:17:53');
INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`, `updated_at`) VALUES ('2', '5', '2', 'Served', '10.00', '2', '2026-05-17 18:13:04', '2026-05-17 18:17:56');
INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`, `updated_at`) VALUES ('3', '5', '3', 'Served', '20.00', '3', '2026-05-17 18:13:47', '2026-05-17 18:18:00');

-- TABLE: order_items for admin_id = 5
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('1', '1', '5', 'quick2', '10.00', '1', '10.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('2', '2', '5', 'quick2', '10.00', '1', '10.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('3', '3', '5', 'quick2', '10.00', '2', '20.00');

-- TABLE: payments for admin_id = 5
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('1', '1', 'Cash', '50.00', '40.00', 'RCP-6A0A051E6318A', 'Completed', '2026-05-17 18:12:46');
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('2', '2', 'Cash', '100.00', '90.00', 'RCP-6A0A053039754', 'Completed', '2026-05-17 18:13:04');
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('3', '3', 'Cash', '50.00', '30.00', 'RCP-6A0A055B344FC', 'Completed', '2026-05-17 18:13:47');

-- TABLE: audit_log (admin_id = 5)

SET FOREIGN_KEY_CHECKS=1;
