-- iPOS Admin Backup | Admin ID: 3 | Label: with_two_orders_and_new_staff_sakura
-- Restaurant: uzumaki ramen | Created: 2026-05-19 14:05:51
-- Generated by iPOS Admin Backup & Recovery

SET FOREIGN_KEY_CHECKS=0;

-- TABLE: menu_items (admin_id = 3)
DELETE FROM `menu_items` WHERE `admin_id` = 3;

INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('7', '3', 'buldak', '', '50.00', '99', 'dry noodles', '1', '../uploads/item_3_1779139422.jpg', '2026-05-18 21:23:48', '2026-05-19 13:50:30');
INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('8', '3', 'nissin ramen', '', '45.00', '199', 'Noodles', '1', '../uploads/item_3_1779197805.jpg', '2026-05-19 13:36:49', '2026-05-19 13:48:53');

-- TABLE: staffs (admin_id = 3)
DELETE FROM `staffs` WHERE `admin_id` = 3;

INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`) VALUES ('2', '3', 'hinata', 'Cashier', '$2y$12$yO4a3pZOFpPfNcOW8thDI.8/wIYh5502PiBVptOtjOLG16SgkG0y.', 'Active', '13:15:00', '17:15:00', '0', NULL, '2026-05-19 13:48:40', '2026-05-15 14:14:35');
INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`) VALUES ('5', '3', 'sakura', 'Cashier', '$2y$12$q0UwR8hS0Btx8uyrsR.T1Or61T8jlqugQQgMT94K5YvsZRm/D8XC6', 'Active', '05:46:00', '18:50:00', '0', NULL, NULL, '2026-05-19 13:47:16');

-- TABLE: orders (admin_id = 3)
DELETE FROM `orders` WHERE `admin_id` = 3;

INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`, `updated_at`) VALUES ('4', '3', '4', 'Queued', '45.00', '1', '2026-05-19 13:48:53', '2026-05-19 13:48:53');
INSERT INTO `orders` (`order_id`, `admin_id`, `customer_id`, `order_status`, `total_amount`, `queue_number`, `created_at`, `updated_at`) VALUES ('5', '3', '5', 'Queued', '50.00', '2', '2026-05-19 13:50:30', '2026-05-19 13:50:30');

-- TABLE: order_items for admin_id = 3
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('4', '4', '8', 'nissin ramen', '45.00', '1', '45.00');
INSERT INTO `order_items` (`order_item_id`, `order_id`, `menu_item_id`, `item_name`, `price`, `quantity`, `subtotal`) VALUES ('5', '5', '7', 'buldak', '50.00', '1', '50.00');

-- TABLE: payments for admin_id = 3
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('4', '4', 'Cash', '100.00', '55.00', 'RCP-6A0C6A459B696', 'Completed', '2026-05-19 13:48:53');
INSERT INTO `payments` (`payment_id`, `order_id`, `payment_method`, `amount_paid`, `change_given`, `receipt_number`, `payment_status`, `payment_date`) VALUES ('5', '5', 'Cash', '100.00', '50.00', 'RCP-6A0C6AA6088A2', 'Completed', '2026-05-19 13:50:30');

-- TABLE: audit_log (admin_id = 3)
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('30', '3', 'uzumaki', 'admin_backup_created', 'backup', NULL, 'backup_manual_20260519_124733.sql', 'Admin backup created: backup_manual_20260519_124733.sql | menu:0, staff:1, orders:0', '::1', '2026-05-19 12:47:34');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('31', '3', 'uzumaki', 'admin_backup_restored', 'backup', NULL, 'backup_manual_20260519_124733.sql', 'Admin database restored from: backup_manual_20260519_124733.sql', '::1', '2026-05-19 13:02:13');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('32', '3', 'uzumaki', 'admin_backup_restored', 'backup', NULL, 'backup_manual_20260519_124733.sql', 'Admin database restored from: backup_manual_20260519_124733.sql', '::1', '2026-05-19 13:05:34');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('33', '3', 'uzumaki', 'admin_backup_restored', 'backup', NULL, 'backup_manual_20260519_124733.sql', 'Admin database restored from: backup_manual_20260519_124733.sql', '::1', '2026-05-19 13:19:51');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('34', '3', 'uzumaki', 'admin_backup_restored', 'backup', NULL, 'backup_manual_20260519_124733.sql', 'Admin database restored from: backup_manual_20260519_124733.sql', '::1', '2026-05-19 13:24:14');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('35', '3', 'uzumaki', 'admin_backup_restored', 'backup', NULL, 'backup_manual_20260519_124733.sql', 'Admin database restored from: backup_manual_20260519_124733.sql', '::1', '2026-05-19 13:27:00');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('44', '3', 'uzumaki', 'admin_backup_created', 'backup', NULL, 'backup_first_backup_for_uzumaki_20260518_211720.sql', 'Admin backup created: backup_first_backup_for_uzumaki_20260518_211720.sql | menu:0, staff:1, orders:0', '::1', '2026-05-18 21:17:20');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('45', '3', 'uzumaki', 'admin_backup_restored', 'backup', NULL, 'backup_new_item_20260518_212441.sql', 'Admin database restored from: backup_new_item_20260518_212441.sql', '::1', '2026-05-19 13:35:14');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('46', '3', 'uzumaki', 'admin_backup_created', 'backup', NULL, 'backup_with_nissin_ramen_new_item_20260519_133704.sql', 'Admin backup created: backup_with_nissin_ramen_new_item_20260519_133704.sql | menu:2, staff:1, orders:0', '::1', '2026-05-19 13:37:04');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('47', '3', 'uzumaki', 'admin_backup_restored', 'backup', NULL, 'backup_manual_20260519_124733.sql', 'Admin database restored from: backup_manual_20260519_124733.sql', '::1', '2026-05-19 13:37:21');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('48', '3', 'uzumaki', 'admin_backup_restored', 'backup', NULL, 'backup_first_backup_for_uzumaki_20260518_211720.sql', 'Admin database restored from: backup_first_backup_for_uzumaki_20260518_211720.sql', '::1', '2026-05-19 13:39:05');
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('49', '3', 'uzumaki', 'admin_backup_restored', 'backup', NULL, 'backup_first_backup_for_uzumaki_20260518_211720.sql', 'Admin database restored from: backup_first_backup_for_uzumaki_20260518_211720.sql', '::1', '2026-05-19 13:42:30');

SET FOREIGN_KEY_CHECKS=1;
