-- iPOS Admin Backup | Admin ID: 3 | Label: manual
-- Restaurant: uzumaki ramen | Created: 2026-05-19 12:47:33
-- Generated by iPOS Admin Backup & Recovery

SET FOREIGN_KEY_CHECKS=0;

-- TABLE: menu_items (admin_id = 3)
DELETE FROM `menu_items` WHERE `admin_id` = 3;


-- TABLE: staffs (admin_id = 3)
DELETE FROM `staffs` WHERE `admin_id` = 3;

INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`) VALUES ('2', '3', 'hinata', 'Cashier', '$2y$12$yO4a3pZOFpPfNcOW8thDI.8/wIYh5502PiBVptOtjOLG16SgkG0y.', 'Active', '13:15:00', '17:15:00', '0', NULL, '2026-05-15 14:15:56', '2026-05-15 14:14:35');

-- TABLE: orders (admin_id = 3)
DELETE FROM `orders` WHERE `admin_id` = 3;


-- TABLE: audit_log (admin_id = 3)

SET FOREIGN_KEY_CHECKS=1;
