-- iPOS Admin Backup | Admin ID: 3 | Label: new_item
-- Restaurant: uzumaki ramen | Created: 2026-05-18 21:24:41
-- Generated by iPOS Admin Backup & Recovery

SET FOREIGN_KEY_CHECKS=0;

-- TABLE: menu_items (admin_id = 3)
DELETE FROM `menu_items` WHERE `admin_id` = 3;

INSERT INTO `menu_items` (`menu_item_id`, `admin_id`, `item_name`, `description`, `price`, `stock_quantity`, `category`, `is_available`, `image_url`, `created_at`, `updated_at`) VALUES ('7', '3', 'buldak', '', '50.00', '100', 'dry noodles', '1', '../uploads/item_3_1779139422.jpg', '2026-05-18 21:23:48', '2026-05-18 21:23:48');

-- TABLE: staffs (admin_id = 3)
DELETE FROM `staffs` WHERE `admin_id` = 3;

INSERT INTO `staffs` (`staff_id`, `admin_id`, `fullname`, `role`, `pin`, `status`, `shift_start`, `shift_end`, `login_fail_count`, `last_fail_at`, `last_login_at`, `created_at`) VALUES ('2', '3', 'hinata', 'Cashier', '$2y$12$yO4a3pZOFpPfNcOW8thDI.8/wIYh5502PiBVptOtjOLG16SgkG0y.', 'Active', '13:15:00', '17:15:00', '0', NULL, '2026-05-15 14:15:56', '2026-05-15 14:14:35');

-- TABLE: orders (admin_id = 3)
DELETE FROM `orders` WHERE `admin_id` = 3;


-- TABLE: audit_log (admin_id = 3)
INSERT INTO `audit_log` (`log_id`, `admin_id`, `actor_name`, `action`, `target_type`, `target_id`, `target_label`, `detail`, `ip_address`, `created_at`) VALUES ('44', '3', 'uzumaki', 'admin_backup_created', 'backup', NULL, 'backup_first_backup_for_uzumaki_20260518_211720.sql', 'Admin backup created: backup_first_backup_for_uzumaki_20260518_211720.sql | menu:0, staff:1, orders:0', '::1', '2026-05-18 21:17:20');

SET FOREIGN_KEY_CHECKS=1;
